package com.ibm.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.ibm.domain.core.AVLName;

import com.ibm.dao.mysql.AVLName_Default_ActivityDao;

import com.ibm.domain.core.IBUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("AVLName_Default_ActivityService")
public class AVLName_Default_ActivityService extends IBBaseService  {
private static Logger log = Logger.getLogger(AVLName_Default_ActivityService.class.getName());

	private AVLName_Default_ActivityDao AVLName_Default_Activity_dao;


	public AVLName_Default_ActivityDao get_AVLName_Default_Activity_dao() {
		return AVLName_Default_Activity_dao;
	}


	@Resource(name="AVLName_Default_ActivityDao")
	public void set_AVLName_Default_Activity_dao(AVLName_Default_ActivityDao AVLName_Default_Activity_dao) {
		this.AVLName_Default_Activity_dao = AVLName_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  AVLName noun into database
	*@param AVLName
	*@param user
	*@return the_AVLName object will return
	*@throws Exception
	*/

	public AVLName create_avlname(AVLName AVLName, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_avlname service operation started !");

		try{
			AVLName the_AVLName;

			the_AVLName = AVLName_Default_Activity_dao.create_avlname(AVLName, user);

 			log.info(" Object returned from create_avlname  service method !");
			return the_AVLName;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_avlname service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  AVLName noun into database
	*@param AVLName
	*@param user
	*@return the_AVLName object will return
	*@throws Exception
	*/

	public AVLName update_avlname(AVLName AVLName, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_avlname service operation started !");

		try{
			AVLName the_AVLName;

			the_AVLName = AVLName_Default_Activity_dao.update_avlname(AVLName, user);

 			log.info(" Object returned from update_avlname  service method !");
			return the_AVLName;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_avlname service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  AVLName noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_AVLName object will return
	*@throws Exception
	*/

	public AVLName avlname_search_for_update(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("avlname_search_for_update service operation started !");

		try{
			AVLName the_AVLName;

			the_AVLName = AVLName_Default_Activity_dao.avlname_search_for_update(id, user);

 			log.info(" Object returned from avlname_search_for_update  service method !");
			return the_AVLName;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("avlname_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  AVLName noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_AVLName id deleted based on id
	*@throws Exception
	*/

	public String  delete_avlname(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_avlname service operation started !");

		try{
			String method_return_message;

			method_return_message = AVLName_Default_Activity_dao.delete_avlname(id, user);

 			log.info(" Object returned from delete_avlname  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_avlname service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  AVLName noun from  database
	*
	*
	*@return List of AVLName object will return
	*@throws Exception
	*/

	public ArrayList<AVLName> get_all_avlname() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<AVLName> AVLName_list;

			AVLName_list = AVLName_Default_Activity_dao.get_all_avlname();

 			log.info(" Object returned from   service method !");
			return AVLName_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}