package com.ibm.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.ibm.domain.core.Forecast;

import com.ibm.dao.mysql.Forecast_Default_ActivityDao;

import com.ibm.domain.core.IBUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Forecast_Default_ActivityService")
public class Forecast_Default_ActivityService extends IBBaseService  {
private static Logger log = Logger.getLogger(Forecast_Default_ActivityService.class.getName());

	private Forecast_Default_ActivityDao Forecast_Default_Activity_dao;


	public Forecast_Default_ActivityDao get_Forecast_Default_Activity_dao() {
		return Forecast_Default_Activity_dao;
	}


	@Resource(name="Forecast_Default_ActivityDao")
	public void set_Forecast_Default_Activity_dao(Forecast_Default_ActivityDao Forecast_Default_Activity_dao) {
		this.Forecast_Default_Activity_dao = Forecast_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Forecast noun into database
	*@param Forecast
	*@param user
	*@return the_Forecast object will return
	*@throws Exception
	*/

	public Forecast create_forecast(Forecast Forecast, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_forecast service operation started !");

		try{
			Forecast the_Forecast;

			the_Forecast = Forecast_Default_Activity_dao.create_forecast(Forecast, user);

 			log.info(" Object returned from create_forecast  service method !");
			return the_Forecast;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_forecast service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Forecast noun into database
	*@param Forecast
	*@param user
	*@return the_Forecast object will return
	*@throws Exception
	*/

	public Forecast update_forecast(Forecast Forecast, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_forecast service operation started !");

		try{
			Forecast the_Forecast;

			the_Forecast = Forecast_Default_Activity_dao.update_forecast(Forecast, user);

 			log.info(" Object returned from update_forecast  service method !");
			return the_Forecast;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_forecast service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Forecast noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Forecast object will return
	*@throws Exception
	*/

	public Forecast forecast_search_for_update(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("forecast_search_for_update service operation started !");

		try{
			Forecast the_Forecast;

			the_Forecast = Forecast_Default_Activity_dao.forecast_search_for_update(id, user);

 			log.info(" Object returned from forecast_search_for_update  service method !");
			return the_Forecast;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("forecast_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Forecast noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Forecast id deleted based on id
	*@throws Exception
	*/

	public String  delete_forecast(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_forecast service operation started !");

		try{
			String method_return_message;

			method_return_message = Forecast_Default_Activity_dao.delete_forecast(id, user);

 			log.info(" Object returned from delete_forecast  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_forecast service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Forecast noun from  database
	*
	*
	*@return List of Forecast object will return
	*@throws Exception
	*/

	public ArrayList<Forecast> get_all_forecast() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Forecast> Forecast_list;

			Forecast_list = Forecast_Default_Activity_dao.get_all_forecast();

 			log.info(" Object returned from   service method !");
			return Forecast_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}