package com.ibm.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.ibm.domain.core.MonthEnd;

import com.ibm.dao.mysql.MonthEnd_Default_ActivityDao;

import com.ibm.domain.core.IBUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("MonthEnd_Default_ActivityService")
public class MonthEnd_Default_ActivityService extends IBBaseService  {
private static Logger log = Logger.getLogger(MonthEnd_Default_ActivityService.class.getName());

	private MonthEnd_Default_ActivityDao MonthEnd_Default_Activity_dao;


	public MonthEnd_Default_ActivityDao get_MonthEnd_Default_Activity_dao() {
		return MonthEnd_Default_Activity_dao;
	}


	@Resource(name="MonthEnd_Default_ActivityDao")
	public void set_MonthEnd_Default_Activity_dao(MonthEnd_Default_ActivityDao MonthEnd_Default_Activity_dao) {
		this.MonthEnd_Default_Activity_dao = MonthEnd_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  MonthEnd noun into database
	*@param MonthEnd
	*@param user
	*@return the_MonthEnd object will return
	*@throws Exception
	*/

	public MonthEnd create_monthend(MonthEnd MonthEnd, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_monthend service operation started !");

		try{
			MonthEnd the_MonthEnd;

			the_MonthEnd = MonthEnd_Default_Activity_dao.create_monthend(MonthEnd, user);

 			log.info(" Object returned from create_monthend  service method !");
			return the_MonthEnd;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_monthend service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  MonthEnd noun into database
	*@param MonthEnd
	*@param user
	*@return the_MonthEnd object will return
	*@throws Exception
	*/

	public MonthEnd update_monthend(MonthEnd MonthEnd, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_monthend service operation started !");

		try{
			MonthEnd the_MonthEnd;

			the_MonthEnd = MonthEnd_Default_Activity_dao.update_monthend(MonthEnd, user);

 			log.info(" Object returned from update_monthend  service method !");
			return the_MonthEnd;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_monthend service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  MonthEnd noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_MonthEnd object will return
	*@throws Exception
	*/

	public MonthEnd monthend_search_for_update(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("monthend_search_for_update service operation started !");

		try{
			MonthEnd the_MonthEnd;

			the_MonthEnd = MonthEnd_Default_Activity_dao.monthend_search_for_update(id, user);

 			log.info(" Object returned from monthend_search_for_update  service method !");
			return the_MonthEnd;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("monthend_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  MonthEnd noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_MonthEnd id deleted based on id
	*@throws Exception
	*/

	public String  delete_monthend(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_monthend service operation started !");

		try{
			String method_return_message;

			method_return_message = MonthEnd_Default_Activity_dao.delete_monthend(id, user);

 			log.info(" Object returned from delete_monthend  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_monthend service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  MonthEnd noun from  database
	*
	*
	*@return List of MonthEnd object will return
	*@throws Exception
	*/

	public ArrayList<MonthEnd> get_all_monthend() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<MonthEnd> MonthEnd_list;

			MonthEnd_list = MonthEnd_Default_Activity_dao.get_all_monthend();

 			log.info(" Object returned from   service method !");
			return MonthEnd_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}