package com.ibm.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.ibm.domain.core.Note;

import com.ibm.dao.mysql.Note_Default_ActivityDao;

import com.ibm.domain.core.IBUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Note_Default_ActivityService")
public class Note_Default_ActivityService extends IBBaseService  {
private static Logger log = Logger.getLogger(Note_Default_ActivityService.class.getName());

	private Note_Default_ActivityDao note_Default_Activity_dao;


	public Note_Default_ActivityDao get_note_Default_Activity_dao() {
		return note_Default_Activity_dao;
	}


	@Resource(name="Note_Default_ActivityDao")
	public void set_note_Default_Activity_dao(Note_Default_ActivityDao note_Default_Activity_dao) {
		this.note_Default_Activity_dao = note_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Note noun into database
	*@param Note
	*@param user
	*@return the_Note object will return
	*@throws Exception
	*/

	public Note create_note(Note Note, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_note service operation started !");

		try{
			Note the_Note;

			the_Note = note_Default_Activity_dao.create_note(Note, user);

 			log.info(" Object returned from create_note  service method !");
			return the_Note;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_note service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Note noun into database
	*@param Note
	*@param user
	*@return the_Note object will return
	*@throws Exception
	*/

	public Note update_note(Note Note, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_note service operation started !");

		try{
			Note the_Note;

			the_Note = note_Default_Activity_dao.update_note(Note, user);

 			log.info(" Object returned from update_note  service method !");
			return the_Note;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_note service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Note noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Note object will return
	*@throws Exception
	*/

	public Note note_search_for_update(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("note_search_for_update service operation started !");

		try{
			Note the_Note;

			the_Note = note_Default_Activity_dao.note_search_for_update(id, user);

 			log.info(" Object returned from note_search_for_update  service method !");
			return the_Note;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("note_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Note noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Note id deleted based on id
	*@throws Exception
	*/

	public String  delete_note(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_note service operation started !");

		try{
			String method_return_message;

			method_return_message = note_Default_Activity_dao.delete_note(id, user);

 			log.info(" Object returned from delete_note  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_note service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Note noun from  database
	*
	*
	*@return List of Note object will return
	*@throws Exception
	*/

	public ArrayList<Note> get_all_note() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Note> Note_list;

			Note_list = note_Default_Activity_dao.get_all_note();

 			log.info(" Object returned from   service method !");
			return Note_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}