package com.ibm.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.ibm.domain.core.Percentage;

import com.ibm.dao.mysql.Percentage_Default_ActivityDao;

import com.ibm.domain.core.IBUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Percentage_Default_ActivityService")
public class Percentage_Default_ActivityService extends IBBaseService  {
private static Logger log = Logger.getLogger(Percentage_Default_ActivityService.class.getName());

	private Percentage_Default_ActivityDao Percentage_Default_Activity_dao;


	public Percentage_Default_ActivityDao get_Percentage_Default_Activity_dao() {
		return Percentage_Default_Activity_dao;
	}


	@Resource(name="Percentage_Default_ActivityDao")
	public void set_Percentage_Default_Activity_dao(Percentage_Default_ActivityDao Percentage_Default_Activity_dao) {
		this.Percentage_Default_Activity_dao = Percentage_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Percentage noun into database
	*@param Percentage
	*@param user
	*@return the_Percentage object will return
	*@throws Exception
	*/

	public Percentage create_percentage(Percentage Percentage, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_percentage service operation started !");

		try{
			Percentage the_Percentage;

			the_Percentage = Percentage_Default_Activity_dao.create_percentage(Percentage, user);

 			log.info(" Object returned from create_percentage  service method !");
			return the_Percentage;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_percentage service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Percentage noun into database
	*@param Percentage
	*@param user
	*@return the_Percentage object will return
	*@throws Exception
	*/

	public Percentage update_percentage(Percentage Percentage, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_percentage service operation started !");

		try{
			Percentage the_Percentage;

			the_Percentage = Percentage_Default_Activity_dao.update_percentage(Percentage, user);

 			log.info(" Object returned from update_percentage  service method !");
			return the_Percentage;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_percentage service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Percentage noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Percentage object will return
	*@throws Exception
	*/

	public Percentage percentage_search_for_update(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("percentage_search_for_update service operation started !");

		try{
			Percentage the_Percentage;

			the_Percentage = Percentage_Default_Activity_dao.percentage_search_for_update(id, user);

 			log.info(" Object returned from percentage_search_for_update  service method !");
			return the_Percentage;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("percentage_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Percentage noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Percentage id deleted based on id
	*@throws Exception
	*/

	public String  delete_percentage(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_percentage service operation started !");

		try{
			String method_return_message;

			method_return_message = Percentage_Default_Activity_dao.delete_percentage(id, user);

 			log.info(" Object returned from delete_percentage  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_percentage service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Percentage noun from  database
	*
	*
	*@return List of Percentage object will return
	*@throws Exception
	*/

	public ArrayList<Percentage> get_all_percentage() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Percentage> Percentage_list;

			Percentage_list = Percentage_Default_Activity_dao.get_all_percentage();

 			log.info(" Object returned from   service method !");
			return Percentage_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}