package com.ibm.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.ibm.domain.core.Practice;

import com.ibm.dao.mysql.Practice_Default_ActivityDao;

import com.ibm.domain.core.IBUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Practice_Default_ActivityService")
public class Practice_Default_ActivityService extends IBBaseService  {
private static Logger log = Logger.getLogger(Practice_Default_ActivityService.class.getName());

	private Practice_Default_ActivityDao Practice_Default_Activity_dao;


	public Practice_Default_ActivityDao get_Practice_Default_Activity_dao() {
		return Practice_Default_Activity_dao;
	}


	@Resource(name="Practice_Default_ActivityDao")
	public void set_Practice_Default_Activity_dao(Practice_Default_ActivityDao Practice_Default_Activity_dao) {
		this.Practice_Default_Activity_dao = Practice_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Practice noun into database
	*@param Practice
	*@param user
	*@return the_Practice object will return
	*@throws Exception
	*/

	public Practice create_practice(Practice Practice, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_practice service operation started !");

		try{
			Practice the_Practice;

			the_Practice = Practice_Default_Activity_dao.create_practice(Practice, user);

 			log.info(" Object returned from create_practice  service method !");
			return the_Practice;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_practice service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Practice noun into database
	*@param Practice
	*@param user
	*@return the_Practice object will return
	*@throws Exception
	*/

	public Practice update_practice(Practice Practice, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_practice service operation started !");

		try{
			Practice the_Practice;

			the_Practice = Practice_Default_Activity_dao.update_practice(Practice, user);

 			log.info(" Object returned from update_practice  service method !");
			return the_Practice;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_practice service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Practice noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Practice object will return
	*@throws Exception
	*/

	public Practice practice_search_for_update(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("practice_search_for_update service operation started !");

		try{
			Practice the_Practice;

			the_Practice = Practice_Default_Activity_dao.practice_search_for_update(id, user);

 			log.info(" Object returned from practice_search_for_update  service method !");
			return the_Practice;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("practice_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Practice noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Practice id deleted based on id
	*@throws Exception
	*/

	public String  delete_practice(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_practice service operation started !");

		try{
			String method_return_message;

			method_return_message = Practice_Default_Activity_dao.delete_practice(id, user);

 			log.info(" Object returned from delete_practice  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_practice service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Practice noun from  database
	*
	*
	*@return List of Practice object will return
	*@throws Exception
	*/

	public ArrayList<Practice> get_all_practice() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Practice> Practice_list;

			Practice_list = Practice_Default_Activity_dao.get_all_practice();

 			log.info(" Object returned from   service method !");
			return Practice_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}