package com.ibm.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.ibm.domain.core.Region;

import com.ibm.dao.mysql.Region_Default_ActivityDao;

import com.ibm.domain.core.IBUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Region_Default_ActivityService")
public class Region_Default_ActivityService extends IBBaseService  {
private static Logger log = Logger.getLogger(Region_Default_ActivityService.class.getName());

	private Region_Default_ActivityDao Region_Default_Activity_dao;


	public Region_Default_ActivityDao get_Region_Default_Activity_dao() {
		return Region_Default_Activity_dao;
	}


	@Resource(name="Region_Default_ActivityDao")
	public void set_Region_Default_Activity_dao(Region_Default_ActivityDao Region_Default_Activity_dao) {
		this.Region_Default_Activity_dao = Region_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Region noun into database
	*@param Region
	*@param user
	*@return the_Region object will return
	*@throws Exception
	*/

	public Region create_region(Region Region, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_region service operation started !");

		try{
			Region the_Region;

			the_Region = Region_Default_Activity_dao.create_region(Region, user);

 			log.info(" Object returned from create_region  service method !");
			return the_Region;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_region service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Region noun into database
	*@param Region
	*@param user
	*@return the_Region object will return
	*@throws Exception
	*/

	public Region update_region(Region Region, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_region service operation started !");

		try{
			Region the_Region;

			the_Region = Region_Default_Activity_dao.update_region(Region, user);

 			log.info(" Object returned from update_region  service method !");
			return the_Region;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_region service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Region noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Region object will return
	*@throws Exception
	*/

	public Region region_search_for_update(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("region_search_for_update service operation started !");

		try{
			Region the_Region;

			the_Region = Region_Default_Activity_dao.region_search_for_update(id, user);

 			log.info(" Object returned from region_search_for_update  service method !");
			return the_Region;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("region_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Region noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Region id deleted based on id
	*@throws Exception
	*/

	public String  delete_region(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_region service operation started !");

		try{
			String method_return_message;

			method_return_message = Region_Default_Activity_dao.delete_region(id, user);

 			log.info(" Object returned from delete_region  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_region service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Region noun from  database
	*
	*
	*@return List of Region object will return
	*@throws Exception
	*/

	public ArrayList<Region> get_all_region() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Region> Region_list;

			Region_list = Region_Default_Activity_dao.get_all_region();

 			log.info(" Object returned from   service method !");
			return Region_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}