package com.ibm.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.ibm.domain.core.RevenueType;

import com.ibm.dao.mysql.RevenueType_Default_ActivityDao;

import com.ibm.domain.core.IBUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("RevenueType_Default_ActivityService")
public class RevenueType_Default_ActivityService extends IBBaseService  {
private static Logger log = Logger.getLogger(RevenueType_Default_ActivityService.class.getName());

	private RevenueType_Default_ActivityDao RevenueType_Default_Activity_dao;


	public RevenueType_Default_ActivityDao get_RevenueType_Default_Activity_dao() {
		return RevenueType_Default_Activity_dao;
	}


	@Resource(name="RevenueType_Default_ActivityDao")
	public void set_RevenueType_Default_Activity_dao(RevenueType_Default_ActivityDao RevenueType_Default_Activity_dao) {
		this.RevenueType_Default_Activity_dao = RevenueType_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  RevenueType noun into database
	*@param RevenueType
	*@param user
	*@return the_RevenueType object will return
	*@throws Exception
	*/

	public RevenueType create_revenuetype(RevenueType RevenueType, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_revenuetype service operation started !");

		try{
			RevenueType the_RevenueType;

			the_RevenueType = RevenueType_Default_Activity_dao.create_revenuetype(RevenueType, user);

 			log.info(" Object returned from create_revenuetype  service method !");
			return the_RevenueType;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_revenuetype service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  RevenueType noun into database
	*@param RevenueType
	*@param user
	*@return the_RevenueType object will return
	*@throws Exception
	*/

	public RevenueType update_revenuetype(RevenueType RevenueType, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_revenuetype service operation started !");

		try{
			RevenueType the_RevenueType;

			the_RevenueType = RevenueType_Default_Activity_dao.update_revenuetype(RevenueType, user);

 			log.info(" Object returned from update_revenuetype  service method !");
			return the_RevenueType;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_revenuetype service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  RevenueType noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_RevenueType object will return
	*@throws Exception
	*/

	public RevenueType revenuetype_search_for_update(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("revenuetype_search_for_update service operation started !");

		try{
			RevenueType the_RevenueType;

			the_RevenueType = RevenueType_Default_Activity_dao.revenuetype_search_for_update(id, user);

 			log.info(" Object returned from revenuetype_search_for_update  service method !");
			return the_RevenueType;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("revenuetype_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  RevenueType noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_RevenueType id deleted based on id
	*@throws Exception
	*/

	public String  delete_revenuetype(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_revenuetype service operation started !");

		try{
			String method_return_message;

			method_return_message = RevenueType_Default_Activity_dao.delete_revenuetype(id, user);

 			log.info(" Object returned from delete_revenuetype  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_revenuetype service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  RevenueType noun from  database
	*
	*
	*@return List of RevenueType object will return
	*@throws Exception
	*/

	public ArrayList<RevenueType> get_all_revenuetype() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<RevenueType> RevenueType_list;

			RevenueType_list = RevenueType_Default_Activity_dao.get_all_revenuetype();

 			log.info(" Object returned from   service method !");
			return RevenueType_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}