package com.ibm.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.ibm.domain.core.Territory;

import com.ibm.dao.mysql.Territory_Default_ActivityDao;

import com.ibm.domain.core.IBUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Territory_Default_ActivityService")
public class Territory_Default_ActivityService extends IBBaseService  {
private static Logger log = Logger.getLogger(Territory_Default_ActivityService.class.getName());

	private Territory_Default_ActivityDao Territory_Default_Activity_dao;


	public Territory_Default_ActivityDao get_Territory_Default_Activity_dao() {
		return Territory_Default_Activity_dao;
	}


	@Resource(name="Territory_Default_ActivityDao")
	public void set_Territory_Default_Activity_dao(Territory_Default_ActivityDao Territory_Default_Activity_dao) {
		this.Territory_Default_Activity_dao = Territory_Default_Activity_dao;
	}



	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform save operation of  Territory noun into database
	*@param Territory
	*@param user
	*@return the_Territory object will return
	*@throws Exception
	*/

	public Territory create_territory(Territory Territory, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("create_territory service operation started !");

		try{
			Territory the_Territory;

			the_Territory = Territory_Default_Activity_dao.create_territory(Territory, user);

 			log.info(" Object returned from create_territory  service method !");
			return the_Territory;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("create_territory service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform update operation of  Territory noun into database
	*@param Territory
	*@param user
	*@return the_Territory object will return
	*@throws Exception
	*/

	public Territory update_territory(Territory Territory, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("update_territory service operation started !");

		try{
			Territory the_Territory;

			the_Territory = Territory_Default_Activity_dao.update_territory(Territory, user);

 			log.info(" Object returned from update_territory  service method !");
			return the_Territory;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("update_territory service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform fetch operation of  Territory noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Territory object will return
	*@throws Exception
	*/

	public Territory territory_search_for_update(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("territory_search_for_update service operation started !");

		try{
			Territory the_Territory;

			the_Territory = Territory_Default_Activity_dao.territory_search_for_update(id, user);

 			log.info(" Object returned from territory_search_for_update  service method !");
			return the_Territory;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("territory_search_for_update service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to perform delete operation of  Territory noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Territory id deleted based on id
	*@throws Exception
	*/

	public String  delete_territory(long id, IBUser user) throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info("delete_territory service operation started !");

		try{
			String method_return_message;

			method_return_message = Territory_Default_Activity_dao.delete_territory(id, user);

 			log.info(" Object returned from delete_territory  service method !");
			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error("delete_territory service throws exception : "+ e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of this service method is to get list of  Territory noun from  database
	*
	*
	*@return List of Territory object will return
	*@throws Exception
	*/

	public ArrayList<Territory> get_all_territory() throws Exception {

 		  log.setLevel(Level.INFO);
	      log.info(" service operation started !");

		try{
			ArrayList<Territory> Territory_list;

			Territory_list = Territory_Default_Activity_dao.get_all_territory();

 			log.info(" Object returned from   service method !");
			return Territory_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());
			log.error(" service throws exception : "+ e.toString());

		}
		return null;



	}




}