package com.ibm.domain.core;

import javax.persistence.Id;

import javax.persistence.Column;

import javax.persistence.Entity;

import javax.persistence.GeneratedValue;

import javax.persistence.OneToMany;

import javax.persistence.Table;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

@Entity
@Table(name="Client")
 @JsonIgnoreProperties(ignoreUnknown = true)
 @JsonInclude(Include.NON_NULL)
 

@ApiModel( value = "Client", description = "this is a client" )
public class Client  implements Serializable  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
	@Id 
 	@GeneratedValue
 	private	long Id;


	@ApiModelProperty( value = "created date", required = true )
	@Column
 	private	String Created_date;


	@ApiModelProperty( value = "created by value", required = true )
	@Column
 	private	long Created_by;


	@ApiModelProperty( value = "updated date", required = true )
	@Column
 	private	String Updated_date;


	@ApiModelProperty( value = "updated by value", required = true )
	@Column
 	private	long Updated_by;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String Clientname;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String Addressone;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String Addresstwo;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String City;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String Stateorprovince;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String Postalcode;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String Country;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String Primarycontactname;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String Primarycontactnamephone;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String Primarycontactemail;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	private	String Notes;




	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}


	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}


	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}


	public long getUpdated_by() {
		return Updated_by;
	}

	public void setClientname(String Clientname) {
		this.Clientname = Clientname;
	}


	public String getClientname() {
		return Clientname;
	}

	public void setAddressone(String Addressone) {
		this.Addressone = Addressone;
	}


	public String getAddressone() {
		return Addressone;
	}

	public void setAddresstwo(String Addresstwo) {
		this.Addresstwo = Addresstwo;
	}


	public String getAddresstwo() {
		return Addresstwo;
	}

	public void setCity(String City) {
		this.City = City;
	}


	public String getCity() {
		return City;
	}

	public void setStateorprovince(String Stateorprovince) {
		this.Stateorprovince = Stateorprovince;
	}


	public String getStateorprovince() {
		return Stateorprovince;
	}

	public void setPostalcode(String Postalcode) {
		this.Postalcode = Postalcode;
	}


	public String getPostalcode() {
		return Postalcode;
	}

	public void setCountry(String Country) {
		this.Country = Country;
	}


	public String getCountry() {
		return Country;
	}

	public void setPrimarycontactname(String Primarycontactname) {
		this.Primarycontactname = Primarycontactname;
	}


	public String getPrimarycontactname() {
		return Primarycontactname;
	}

	public void setPrimarycontactnamephone(String Primarycontactnamephone) {
		this.Primarycontactnamephone = Primarycontactnamephone;
	}


	public String getPrimarycontactnamephone() {
		return Primarycontactnamephone;
	}

	public void setPrimarycontactemail(String Primarycontactemail) {
		this.Primarycontactemail = Primarycontactemail;
	}


	public String getPrimarycontactemail() {
		return Primarycontactemail;
	}

	public void setNotes(String Notes) {
		this.Notes = Notes;
	}


	public String getNotes() {
		return Notes;
	}




}