package com.ibm.domain.core;

import javax.persistence.Id;

import javax.persistence.Column;

import javax.persistence.Entity;

import javax.persistence.GeneratedValue;

import javax.persistence.OneToMany;

import javax.persistence.Table;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

@Entity
@Table(name="Forecast")
 @JsonIgnoreProperties(ignoreUnknown = true)
 @JsonInclude(Include.NON_NULL)
 

@ApiModel( value = "Forecast", description = "Forecast" )
public class Forecast  implements Serializable  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
	@Id 
 	@GeneratedValue
 	private	long Id;


	@ApiModelProperty( value = "created date", required = true )
	@Column
 	private	String Created_date;


	@ApiModelProperty( value = "created by value", required = true )
	@Column
 	private	long Created_by;


	@ApiModelProperty( value = "updated date", required = true )
	@Column
 	private	String Updated_date;


	@ApiModelProperty( value = "updated by value", required = true )
	@Column
 	private	long Updated_by;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lotusseller_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Quarter;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Nextsteps;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Oldforecasttype;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lastupdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Unid;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Businesspartner;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Oldestsigndate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Projdur;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String History;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Rolesuser;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Peer_et;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Callamount;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Estsigndate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Technology;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lotusseller;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Pipelineagedate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Pricecaselink;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Actsigndate_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Doclink;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Pba_et;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Oldprojdur;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Sowcurrency;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Pgtyp;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Client;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Spif;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Territory;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bso_et;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Nextstepslast;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Roles;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Condeldate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Engagementmanager;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Project;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Keytrans;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Oldprjstartdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Forecast;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Sowamount;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Region;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Pa_et;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactstate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Revenuetype;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Weekp;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Mthadjfst;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Calldate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Practice;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Linkyesno;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Avpoffering;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bdm;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Prjstartdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Sa;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Oldsowamount;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactphone;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Legal_et;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactcity;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Commentsdisplay;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ics_et;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Avpleadsource;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Sendforecastuser;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Avpsale;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Forecastsw;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Tda_et;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Forecastview;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Oppassessment;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cancelled;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Conexpdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Mdoc;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Freqfly;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ssr;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Strpipelineagedate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactstreetaddress;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactemail;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Del_et;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Sendforecastsw;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Forecasttype;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Salesincentive;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Pm;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactname;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ca_et;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Dbserver;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Quote;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Mqtr;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Qtr;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Mthforecast;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Yrmth;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Qtradjfct;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Qtrforecast;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Forecastdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Product_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Product_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Nextstepsnotes;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Aemail_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lname_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Onsitedays_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Onsitedays_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Avpoffering_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Technology_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Technology_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Avpoffering_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contacticn;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Products;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cellnumber_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactentnumber;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Acomments_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Percentage_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Percentage_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Namedcallers_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Namedcallers_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Arole_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Fname_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Practice_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bluepages_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Practice_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactpanumber;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Sowamount_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Productrelease;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Aemail_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Aemail_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lname_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lname_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Arole_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Arole_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Fname_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Fname_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Commentaction;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Productsver;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactssexpdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactssspend;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Eosdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bluepages_5;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bluepages_6;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bluepages_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bluepages_4;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bluepages_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Reupgradeplan;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Aemail_6;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Aemail_4;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Aemail_5;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cellnumber_4;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cellnumber_5;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cellnumber_6;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cellnumber_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cellnumber_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Fname_6;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Arole_5;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Arole_4;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Fname_4;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Fname_5;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Arole_6;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cemail_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cfirst_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Crole_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ccell_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Acomments_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactcountry;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cemail_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cfirst_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Clast_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Acomments_4;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Acomments_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Nextstepdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Clast_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Crole_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ccell_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Acomments_5;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cpostal_2;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cemail_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cfirst_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Clast_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Crole_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ccell_3;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cemail_5;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cemail_4;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Clast_4;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Clast_5;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cfirst_4;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cfirst_5;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Crole_5;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Crole_4;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Nextstepsnotesadd;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ssr_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cemail_7;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cemail_6;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cfirst_6;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cfirst_7;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Clast_6;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Clast_7;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ccell_7;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactpostalcode;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Aemail_7;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cellnumber_7;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Acomments_7;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Acomments_6;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bluepages_7;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Fname_7;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ccity_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cpostal_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Cstate_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Clocation_1;




	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}


	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}


	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}


	public long getUpdated_by() {
		return Updated_by;
	}

	public void setLotusseller_1(String Lotusseller_1) {
		this.Lotusseller_1 = Lotusseller_1;
	}


	public String getLotusseller_1() {
		return Lotusseller_1;
	}

	public void setQuarter(String Quarter) {
		this.Quarter = Quarter;
	}


	public String getQuarter() {
		return Quarter;
	}

	public void setNextsteps(String Nextsteps) {
		this.Nextsteps = Nextsteps;
	}


	public String getNextsteps() {
		return Nextsteps;
	}

	public void setOldforecasttype(String Oldforecasttype) {
		this.Oldforecasttype = Oldforecasttype;
	}


	public String getOldforecasttype() {
		return Oldforecasttype;
	}

	public void setLastupdate(String Lastupdate) {
		this.Lastupdate = Lastupdate;
	}


	public String getLastupdate() {
		return Lastupdate;
	}

	public void setUnid(String Unid) {
		this.Unid = Unid;
	}


	public String getUnid() {
		return Unid;
	}

	public void setBusinesspartner(String Businesspartner) {
		this.Businesspartner = Businesspartner;
	}


	public String getBusinesspartner() {
		return Businesspartner;
	}

	public void setOldestsigndate(String Oldestsigndate) {
		this.Oldestsigndate = Oldestsigndate;
	}


	public String getOldestsigndate() {
		return Oldestsigndate;
	}

	public void setProjdur(String Projdur) {
		this.Projdur = Projdur;
	}


	public String getProjdur() {
		return Projdur;
	}

	public void setHistory(String History) {
		this.History = History;
	}


	public String getHistory() {
		return History;
	}

	public void setRolesuser(String Rolesuser) {
		this.Rolesuser = Rolesuser;
	}


	public String getRolesuser() {
		return Rolesuser;
	}

	public void setPeer_et(String Peer_et) {
		this.Peer_et = Peer_et;
	}


	public String getPeer_et() {
		return Peer_et;
	}

	public void setCallamount(String Callamount) {
		this.Callamount = Callamount;
	}


	public String getCallamount() {
		return Callamount;
	}

	public void setEstsigndate(String Estsigndate) {
		this.Estsigndate = Estsigndate;
	}


	public String getEstsigndate() {
		return Estsigndate;
	}

	public void setTechnology(String Technology) {
		this.Technology = Technology;
	}


	public String getTechnology() {
		return Technology;
	}

	public void setLotusseller(String Lotusseller) {
		this.Lotusseller = Lotusseller;
	}


	public String getLotusseller() {
		return Lotusseller;
	}

	public void setPipelineagedate(String Pipelineagedate) {
		this.Pipelineagedate = Pipelineagedate;
	}


	public String getPipelineagedate() {
		return Pipelineagedate;
	}

	public void setPricecaselink(String Pricecaselink) {
		this.Pricecaselink = Pricecaselink;
	}


	public String getPricecaselink() {
		return Pricecaselink;
	}

	public void setActsigndate_1(String Actsigndate_1) {
		this.Actsigndate_1 = Actsigndate_1;
	}


	public String getActsigndate_1() {
		return Actsigndate_1;
	}

	public void setDoclink(String Doclink) {
		this.Doclink = Doclink;
	}


	public String getDoclink() {
		return Doclink;
	}

	public void setPba_et(String Pba_et) {
		this.Pba_et = Pba_et;
	}


	public String getPba_et() {
		return Pba_et;
	}

	public void setOldprojdur(String Oldprojdur) {
		this.Oldprojdur = Oldprojdur;
	}


	public String getOldprojdur() {
		return Oldprojdur;
	}

	public void setSowcurrency(String Sowcurrency) {
		this.Sowcurrency = Sowcurrency;
	}


	public String getSowcurrency() {
		return Sowcurrency;
	}

	public void setPgtyp(String Pgtyp) {
		this.Pgtyp = Pgtyp;
	}


	public String getPgtyp() {
		return Pgtyp;
	}

	public void setClient(String Client) {
		this.Client = Client;
	}


	public String getClient() {
		return Client;
	}

	public void setSpif(String Spif) {
		this.Spif = Spif;
	}


	public String getSpif() {
		return Spif;
	}

	public void setTerritory(String Territory) {
		this.Territory = Territory;
	}


	public String getTerritory() {
		return Territory;
	}

	public void setBso_et(String Bso_et) {
		this.Bso_et = Bso_et;
	}


	public String getBso_et() {
		return Bso_et;
	}

	public void setNextstepslast(String Nextstepslast) {
		this.Nextstepslast = Nextstepslast;
	}


	public String getNextstepslast() {
		return Nextstepslast;
	}

	public void setRoles(String Roles) {
		this.Roles = Roles;
	}


	public String getRoles() {
		return Roles;
	}

	public void setCondeldate(String Condeldate) {
		this.Condeldate = Condeldate;
	}


	public String getCondeldate() {
		return Condeldate;
	}

	public void setEngagementmanager(String Engagementmanager) {
		this.Engagementmanager = Engagementmanager;
	}


	public String getEngagementmanager() {
		return Engagementmanager;
	}

	public void setProject(String Project) {
		this.Project = Project;
	}


	public String getProject() {
		return Project;
	}

	public void setKeytrans(String Keytrans) {
		this.Keytrans = Keytrans;
	}


	public String getKeytrans() {
		return Keytrans;
	}

	public void setOldprjstartdate(String Oldprjstartdate) {
		this.Oldprjstartdate = Oldprjstartdate;
	}


	public String getOldprjstartdate() {
		return Oldprjstartdate;
	}

	public void setForecast(String Forecast) {
		this.Forecast = Forecast;
	}


	public String getForecast() {
		return Forecast;
	}

	public void setSowamount(String Sowamount) {
		this.Sowamount = Sowamount;
	}


	public String getSowamount() {
		return Sowamount;
	}

	public void setRegion(String Region) {
		this.Region = Region;
	}


	public String getRegion() {
		return Region;
	}

	public void setPa_et(String Pa_et) {
		this.Pa_et = Pa_et;
	}


	public String getPa_et() {
		return Pa_et;
	}

	public void setContactstate(String Contactstate) {
		this.Contactstate = Contactstate;
	}


	public String getContactstate() {
		return Contactstate;
	}

	public void setRevenuetype(String Revenuetype) {
		this.Revenuetype = Revenuetype;
	}


	public String getRevenuetype() {
		return Revenuetype;
	}

	public void setWeekp(String Weekp) {
		this.Weekp = Weekp;
	}


	public String getWeekp() {
		return Weekp;
	}

	public void setMthadjfst(String Mthadjfst) {
		this.Mthadjfst = Mthadjfst;
	}


	public String getMthadjfst() {
		return Mthadjfst;
	}

	public void setCalldate(String Calldate) {
		this.Calldate = Calldate;
	}


	public String getCalldate() {
		return Calldate;
	}

	public void setPractice(String Practice) {
		this.Practice = Practice;
	}


	public String getPractice() {
		return Practice;
	}

	public void setLinkyesno(String Linkyesno) {
		this.Linkyesno = Linkyesno;
	}


	public String getLinkyesno() {
		return Linkyesno;
	}

	public void setAvpoffering(String Avpoffering) {
		this.Avpoffering = Avpoffering;
	}


	public String getAvpoffering() {
		return Avpoffering;
	}

	public void setBdm(String Bdm) {
		this.Bdm = Bdm;
	}


	public String getBdm() {
		return Bdm;
	}

	public void setPrjstartdate(String Prjstartdate) {
		this.Prjstartdate = Prjstartdate;
	}


	public String getPrjstartdate() {
		return Prjstartdate;
	}

	public void setSa(String Sa) {
		this.Sa = Sa;
	}


	public String getSa() {
		return Sa;
	}

	public void setOldsowamount(String Oldsowamount) {
		this.Oldsowamount = Oldsowamount;
	}


	public String getOldsowamount() {
		return Oldsowamount;
	}

	public void setContactphone(String Contactphone) {
		this.Contactphone = Contactphone;
	}


	public String getContactphone() {
		return Contactphone;
	}

	public void setLegal_et(String Legal_et) {
		this.Legal_et = Legal_et;
	}


	public String getLegal_et() {
		return Legal_et;
	}

	public void setContactcity(String Contactcity) {
		this.Contactcity = Contactcity;
	}


	public String getContactcity() {
		return Contactcity;
	}

	public void setCommentsdisplay(String Commentsdisplay) {
		this.Commentsdisplay = Commentsdisplay;
	}


	public String getCommentsdisplay() {
		return Commentsdisplay;
	}

	public void setIcs_et(String Ics_et) {
		this.Ics_et = Ics_et;
	}


	public String getIcs_et() {
		return Ics_et;
	}

	public void setAvpleadsource(String Avpleadsource) {
		this.Avpleadsource = Avpleadsource;
	}


	public String getAvpleadsource() {
		return Avpleadsource;
	}

	public void setSendforecastuser(String Sendforecastuser) {
		this.Sendforecastuser = Sendforecastuser;
	}


	public String getSendforecastuser() {
		return Sendforecastuser;
	}

	public void setAvpsale(String Avpsale) {
		this.Avpsale = Avpsale;
	}


	public String getAvpsale() {
		return Avpsale;
	}

	public void setForecastsw(String Forecastsw) {
		this.Forecastsw = Forecastsw;
	}


	public String getForecastsw() {
		return Forecastsw;
	}

	public void setTda_et(String Tda_et) {
		this.Tda_et = Tda_et;
	}


	public String getTda_et() {
		return Tda_et;
	}

	public void setForecastview(String Forecastview) {
		this.Forecastview = Forecastview;
	}


	public String getForecastview() {
		return Forecastview;
	}

	public void setOppassessment(String Oppassessment) {
		this.Oppassessment = Oppassessment;
	}


	public String getOppassessment() {
		return Oppassessment;
	}

	public void setCancelled(String Cancelled) {
		this.Cancelled = Cancelled;
	}


	public String getCancelled() {
		return Cancelled;
	}

	public void setConexpdate(String Conexpdate) {
		this.Conexpdate = Conexpdate;
	}


	public String getConexpdate() {
		return Conexpdate;
	}

	public void setMdoc(String Mdoc) {
		this.Mdoc = Mdoc;
	}


	public String getMdoc() {
		return Mdoc;
	}

	public void setFreqfly(String Freqfly) {
		this.Freqfly = Freqfly;
	}


	public String getFreqfly() {
		return Freqfly;
	}

	public void setSsr(String Ssr) {
		this.Ssr = Ssr;
	}


	public String getSsr() {
		return Ssr;
	}

	public void setStrpipelineagedate(String Strpipelineagedate) {
		this.Strpipelineagedate = Strpipelineagedate;
	}


	public String getStrpipelineagedate() {
		return Strpipelineagedate;
	}

	public void setContactstreetaddress(String Contactstreetaddress) {
		this.Contactstreetaddress = Contactstreetaddress;
	}


	public String getContactstreetaddress() {
		return Contactstreetaddress;
	}

	public void setContactemail(String Contactemail) {
		this.Contactemail = Contactemail;
	}


	public String getContactemail() {
		return Contactemail;
	}

	public void setDel_et(String Del_et) {
		this.Del_et = Del_et;
	}


	public String getDel_et() {
		return Del_et;
	}

	public void setSendforecastsw(String Sendforecastsw) {
		this.Sendforecastsw = Sendforecastsw;
	}


	public String getSendforecastsw() {
		return Sendforecastsw;
	}

	public void setForecasttype(String Forecasttype) {
		this.Forecasttype = Forecasttype;
	}


	public String getForecasttype() {
		return Forecasttype;
	}

	public void setSalesincentive(String Salesincentive) {
		this.Salesincentive = Salesincentive;
	}


	public String getSalesincentive() {
		return Salesincentive;
	}

	public void setPm(String Pm) {
		this.Pm = Pm;
	}


	public String getPm() {
		return Pm;
	}

	public void setContactname(String Contactname) {
		this.Contactname = Contactname;
	}


	public String getContactname() {
		return Contactname;
	}

	public void setCa_et(String Ca_et) {
		this.Ca_et = Ca_et;
	}


	public String getCa_et() {
		return Ca_et;
	}

	public void setDbserver(String Dbserver) {
		this.Dbserver = Dbserver;
	}


	public String getDbserver() {
		return Dbserver;
	}

	public void setQuote(String Quote) {
		this.Quote = Quote;
	}


	public String getQuote() {
		return Quote;
	}

	public void setMqtr(String Mqtr) {
		this.Mqtr = Mqtr;
	}


	public String getMqtr() {
		return Mqtr;
	}

	public void setQtr(String Qtr) {
		this.Qtr = Qtr;
	}


	public String getQtr() {
		return Qtr;
	}

	public void setMthforecast(String Mthforecast) {
		this.Mthforecast = Mthforecast;
	}


	public String getMthforecast() {
		return Mthforecast;
	}

	public void setYrmth(String Yrmth) {
		this.Yrmth = Yrmth;
	}


	public String getYrmth() {
		return Yrmth;
	}

	public void setQtradjfct(String Qtradjfct) {
		this.Qtradjfct = Qtradjfct;
	}


	public String getQtradjfct() {
		return Qtradjfct;
	}

	public void setQtrforecast(String Qtrforecast) {
		this.Qtrforecast = Qtrforecast;
	}


	public String getQtrforecast() {
		return Qtrforecast;
	}

	public void setForecastdate(String Forecastdate) {
		this.Forecastdate = Forecastdate;
	}


	public String getForecastdate() {
		return Forecastdate;
	}

	public void setProduct_1(String Product_1) {
		this.Product_1 = Product_1;
	}


	public String getProduct_1() {
		return Product_1;
	}

	public void setProduct_2(String Product_2) {
		this.Product_2 = Product_2;
	}


	public String getProduct_2() {
		return Product_2;
	}

	public void setNextstepsnotes(String Nextstepsnotes) {
		this.Nextstepsnotes = Nextstepsnotes;
	}


	public String getNextstepsnotes() {
		return Nextstepsnotes;
	}

	public void setAemail_1(String Aemail_1) {
		this.Aemail_1 = Aemail_1;
	}


	public String getAemail_1() {
		return Aemail_1;
	}

	public void setLname_1(String Lname_1) {
		this.Lname_1 = Lname_1;
	}


	public String getLname_1() {
		return Lname_1;
	}

	public void setOnsitedays_2(String Onsitedays_2) {
		this.Onsitedays_2 = Onsitedays_2;
	}


	public String getOnsitedays_2() {
		return Onsitedays_2;
	}

	public void setOnsitedays_1(String Onsitedays_1) {
		this.Onsitedays_1 = Onsitedays_1;
	}


	public String getOnsitedays_1() {
		return Onsitedays_1;
	}

	public void setAvpoffering_1(String Avpoffering_1) {
		this.Avpoffering_1 = Avpoffering_1;
	}


	public String getAvpoffering_1() {
		return Avpoffering_1;
	}

	public void setTechnology_2(String Technology_2) {
		this.Technology_2 = Technology_2;
	}


	public String getTechnology_2() {
		return Technology_2;
	}

	public void setTechnology_1(String Technology_1) {
		this.Technology_1 = Technology_1;
	}


	public String getTechnology_1() {
		return Technology_1;
	}

	public void setAvpoffering_2(String Avpoffering_2) {
		this.Avpoffering_2 = Avpoffering_2;
	}


	public String getAvpoffering_2() {
		return Avpoffering_2;
	}

	public void setContacticn(String Contacticn) {
		this.Contacticn = Contacticn;
	}


	public String getContacticn() {
		return Contacticn;
	}

	public void setProducts(String Products) {
		this.Products = Products;
	}


	public String getProducts() {
		return Products;
	}

	public void setCellnumber_1(String Cellnumber_1) {
		this.Cellnumber_1 = Cellnumber_1;
	}


	public String getCellnumber_1() {
		return Cellnumber_1;
	}

	public void setContactentnumber(String Contactentnumber) {
		this.Contactentnumber = Contactentnumber;
	}


	public String getContactentnumber() {
		return Contactentnumber;
	}

	public void setAcomments_1(String Acomments_1) {
		this.Acomments_1 = Acomments_1;
	}


	public String getAcomments_1() {
		return Acomments_1;
	}

	public void setPercentage_2(String Percentage_2) {
		this.Percentage_2 = Percentage_2;
	}


	public String getPercentage_2() {
		return Percentage_2;
	}

	public void setPercentage_1(String Percentage_1) {
		this.Percentage_1 = Percentage_1;
	}


	public String getPercentage_1() {
		return Percentage_1;
	}

	public void setNamedcallers_2(String Namedcallers_2) {
		this.Namedcallers_2 = Namedcallers_2;
	}


	public String getNamedcallers_2() {
		return Namedcallers_2;
	}

	public void setNamedcallers_1(String Namedcallers_1) {
		this.Namedcallers_1 = Namedcallers_1;
	}


	public String getNamedcallers_1() {
		return Namedcallers_1;
	}

	public void setArole_1(String Arole_1) {
		this.Arole_1 = Arole_1;
	}


	public String getArole_1() {
		return Arole_1;
	}

	public void setFname_1(String Fname_1) {
		this.Fname_1 = Fname_1;
	}


	public String getFname_1() {
		return Fname_1;
	}

	public void setPractice_1(String Practice_1) {
		this.Practice_1 = Practice_1;
	}


	public String getPractice_1() {
		return Practice_1;
	}

	public void setBluepages_1(String Bluepages_1) {
		this.Bluepages_1 = Bluepages_1;
	}


	public String getBluepages_1() {
		return Bluepages_1;
	}

	public void setPractice_2(String Practice_2) {
		this.Practice_2 = Practice_2;
	}


	public String getPractice_2() {
		return Practice_2;
	}

	public void setContactpanumber(String Contactpanumber) {
		this.Contactpanumber = Contactpanumber;
	}


	public String getContactpanumber() {
		return Contactpanumber;
	}

	public void setSowamount_1(String Sowamount_1) {
		this.Sowamount_1 = Sowamount_1;
	}


	public String getSowamount_1() {
		return Sowamount_1;
	}

	public void setProductrelease(String Productrelease) {
		this.Productrelease = Productrelease;
	}


	public String getProductrelease() {
		return Productrelease;
	}

	public void setAemail_2(String Aemail_2) {
		this.Aemail_2 = Aemail_2;
	}


	public String getAemail_2() {
		return Aemail_2;
	}

	public void setAemail_3(String Aemail_3) {
		this.Aemail_3 = Aemail_3;
	}


	public String getAemail_3() {
		return Aemail_3;
	}

	public void setLname_3(String Lname_3) {
		this.Lname_3 = Lname_3;
	}


	public String getLname_3() {
		return Lname_3;
	}

	public void setLname_2(String Lname_2) {
		this.Lname_2 = Lname_2;
	}


	public String getLname_2() {
		return Lname_2;
	}

	public void setArole_3(String Arole_3) {
		this.Arole_3 = Arole_3;
	}


	public String getArole_3() {
		return Arole_3;
	}

	public void setArole_2(String Arole_2) {
		this.Arole_2 = Arole_2;
	}


	public String getArole_2() {
		return Arole_2;
	}

	public void setFname_2(String Fname_2) {
		this.Fname_2 = Fname_2;
	}


	public String getFname_2() {
		return Fname_2;
	}

	public void setFname_3(String Fname_3) {
		this.Fname_3 = Fname_3;
	}


	public String getFname_3() {
		return Fname_3;
	}

	public void setCommentaction(String Commentaction) {
		this.Commentaction = Commentaction;
	}


	public String getCommentaction() {
		return Commentaction;
	}

	public void setProductsver(String Productsver) {
		this.Productsver = Productsver;
	}


	public String getProductsver() {
		return Productsver;
	}

	public void setContactssexpdate(String Contactssexpdate) {
		this.Contactssexpdate = Contactssexpdate;
	}


	public String getContactssexpdate() {
		return Contactssexpdate;
	}

	public void setContactssspend(String Contactssspend) {
		this.Contactssspend = Contactssspend;
	}


	public String getContactssspend() {
		return Contactssspend;
	}

	public void setEosdate(String Eosdate) {
		this.Eosdate = Eosdate;
	}


	public String getEosdate() {
		return Eosdate;
	}

	public void setBluepages_5(String Bluepages_5) {
		this.Bluepages_5 = Bluepages_5;
	}


	public String getBluepages_5() {
		return Bluepages_5;
	}

	public void setBluepages_6(String Bluepages_6) {
		this.Bluepages_6 = Bluepages_6;
	}


	public String getBluepages_6() {
		return Bluepages_6;
	}

	public void setBluepages_3(String Bluepages_3) {
		this.Bluepages_3 = Bluepages_3;
	}


	public String getBluepages_3() {
		return Bluepages_3;
	}

	public void setBluepages_4(String Bluepages_4) {
		this.Bluepages_4 = Bluepages_4;
	}


	public String getBluepages_4() {
		return Bluepages_4;
	}

	public void setBluepages_2(String Bluepages_2) {
		this.Bluepages_2 = Bluepages_2;
	}


	public String getBluepages_2() {
		return Bluepages_2;
	}

	public void setReupgradeplan(String Reupgradeplan) {
		this.Reupgradeplan = Reupgradeplan;
	}


	public String getReupgradeplan() {
		return Reupgradeplan;
	}

	public void setAemail_6(String Aemail_6) {
		this.Aemail_6 = Aemail_6;
	}


	public String getAemail_6() {
		return Aemail_6;
	}

	public void setAemail_4(String Aemail_4) {
		this.Aemail_4 = Aemail_4;
	}


	public String getAemail_4() {
		return Aemail_4;
	}

	public void setAemail_5(String Aemail_5) {
		this.Aemail_5 = Aemail_5;
	}


	public String getAemail_5() {
		return Aemail_5;
	}

	public void setCellnumber_4(String Cellnumber_4) {
		this.Cellnumber_4 = Cellnumber_4;
	}


	public String getCellnumber_4() {
		return Cellnumber_4;
	}

	public void setCellnumber_5(String Cellnumber_5) {
		this.Cellnumber_5 = Cellnumber_5;
	}


	public String getCellnumber_5() {
		return Cellnumber_5;
	}

	public void setCellnumber_6(String Cellnumber_6) {
		this.Cellnumber_6 = Cellnumber_6;
	}


	public String getCellnumber_6() {
		return Cellnumber_6;
	}

	public void setCellnumber_2(String Cellnumber_2) {
		this.Cellnumber_2 = Cellnumber_2;
	}


	public String getCellnumber_2() {
		return Cellnumber_2;
	}

	public void setCellnumber_3(String Cellnumber_3) {
		this.Cellnumber_3 = Cellnumber_3;
	}


	public String getCellnumber_3() {
		return Cellnumber_3;
	}

	public void setFname_6(String Fname_6) {
		this.Fname_6 = Fname_6;
	}


	public String getFname_6() {
		return Fname_6;
	}

	public void setArole_5(String Arole_5) {
		this.Arole_5 = Arole_5;
	}


	public String getArole_5() {
		return Arole_5;
	}

	public void setArole_4(String Arole_4) {
		this.Arole_4 = Arole_4;
	}


	public String getArole_4() {
		return Arole_4;
	}

	public void setFname_4(String Fname_4) {
		this.Fname_4 = Fname_4;
	}


	public String getFname_4() {
		return Fname_4;
	}

	public void setFname_5(String Fname_5) {
		this.Fname_5 = Fname_5;
	}


	public String getFname_5() {
		return Fname_5;
	}

	public void setArole_6(String Arole_6) {
		this.Arole_6 = Arole_6;
	}


	public String getArole_6() {
		return Arole_6;
	}

	public void setCemail_1(String Cemail_1) {
		this.Cemail_1 = Cemail_1;
	}


	public String getCemail_1() {
		return Cemail_1;
	}

	public void setCfirst_1(String Cfirst_1) {
		this.Cfirst_1 = Cfirst_1;
	}


	public String getCfirst_1() {
		return Cfirst_1;
	}

	public void setCrole_1(String Crole_1) {
		this.Crole_1 = Crole_1;
	}


	public String getCrole_1() {
		return Crole_1;
	}

	public void setCcell_1(String Ccell_1) {
		this.Ccell_1 = Ccell_1;
	}


	public String getCcell_1() {
		return Ccell_1;
	}

	public void setAcomments_2(String Acomments_2) {
		this.Acomments_2 = Acomments_2;
	}


	public String getAcomments_2() {
		return Acomments_2;
	}

	public void setContactcountry(String Contactcountry) {
		this.Contactcountry = Contactcountry;
	}


	public String getContactcountry() {
		return Contactcountry;
	}

	public void setCemail_2(String Cemail_2) {
		this.Cemail_2 = Cemail_2;
	}


	public String getCemail_2() {
		return Cemail_2;
	}

	public void setCfirst_2(String Cfirst_2) {
		this.Cfirst_2 = Cfirst_2;
	}


	public String getCfirst_2() {
		return Cfirst_2;
	}

	public void setClast_1(String Clast_1) {
		this.Clast_1 = Clast_1;
	}


	public String getClast_1() {
		return Clast_1;
	}

	public void setAcomments_4(String Acomments_4) {
		this.Acomments_4 = Acomments_4;
	}


	public String getAcomments_4() {
		return Acomments_4;
	}

	public void setAcomments_3(String Acomments_3) {
		this.Acomments_3 = Acomments_3;
	}


	public String getAcomments_3() {
		return Acomments_3;
	}

	public void setNextstepdate(String Nextstepdate) {
		this.Nextstepdate = Nextstepdate;
	}


	public String getNextstepdate() {
		return Nextstepdate;
	}

	public void setClast_2(String Clast_2) {
		this.Clast_2 = Clast_2;
	}


	public String getClast_2() {
		return Clast_2;
	}

	public void setCrole_2(String Crole_2) {
		this.Crole_2 = Crole_2;
	}


	public String getCrole_2() {
		return Crole_2;
	}

	public void setCcell_2(String Ccell_2) {
		this.Ccell_2 = Ccell_2;
	}


	public String getCcell_2() {
		return Ccell_2;
	}

	public void setAcomments_5(String Acomments_5) {
		this.Acomments_5 = Acomments_5;
	}


	public String getAcomments_5() {
		return Acomments_5;
	}

	public void setCpostal_2(String Cpostal_2) {
		this.Cpostal_2 = Cpostal_2;
	}


	public String getCpostal_2() {
		return Cpostal_2;
	}

	public void setCemail_3(String Cemail_3) {
		this.Cemail_3 = Cemail_3;
	}


	public String getCemail_3() {
		return Cemail_3;
	}

	public void setCfirst_3(String Cfirst_3) {
		this.Cfirst_3 = Cfirst_3;
	}


	public String getCfirst_3() {
		return Cfirst_3;
	}

	public void setClast_3(String Clast_3) {
		this.Clast_3 = Clast_3;
	}


	public String getClast_3() {
		return Clast_3;
	}

	public void setCrole_3(String Crole_3) {
		this.Crole_3 = Crole_3;
	}


	public String getCrole_3() {
		return Crole_3;
	}

	public void setCcell_3(String Ccell_3) {
		this.Ccell_3 = Ccell_3;
	}


	public String getCcell_3() {
		return Ccell_3;
	}

	public void setCemail_5(String Cemail_5) {
		this.Cemail_5 = Cemail_5;
	}


	public String getCemail_5() {
		return Cemail_5;
	}

	public void setCemail_4(String Cemail_4) {
		this.Cemail_4 = Cemail_4;
	}


	public String getCemail_4() {
		return Cemail_4;
	}

	public void setClast_4(String Clast_4) {
		this.Clast_4 = Clast_4;
	}


	public String getClast_4() {
		return Clast_4;
	}

	public void setClast_5(String Clast_5) {
		this.Clast_5 = Clast_5;
	}


	public String getClast_5() {
		return Clast_5;
	}

	public void setCfirst_4(String Cfirst_4) {
		this.Cfirst_4 = Cfirst_4;
	}


	public String getCfirst_4() {
		return Cfirst_4;
	}

	public void setCfirst_5(String Cfirst_5) {
		this.Cfirst_5 = Cfirst_5;
	}


	public String getCfirst_5() {
		return Cfirst_5;
	}

	public void setCrole_5(String Crole_5) {
		this.Crole_5 = Crole_5;
	}


	public String getCrole_5() {
		return Crole_5;
	}

	public void setCrole_4(String Crole_4) {
		this.Crole_4 = Crole_4;
	}


	public String getCrole_4() {
		return Crole_4;
	}

	public void setNextstepsnotesadd(String Nextstepsnotesadd) {
		this.Nextstepsnotesadd = Nextstepsnotesadd;
	}


	public String getNextstepsnotesadd() {
		return Nextstepsnotesadd;
	}

	public void setSsr_1(String Ssr_1) {
		this.Ssr_1 = Ssr_1;
	}


	public String getSsr_1() {
		return Ssr_1;
	}

	public void setCemail_7(String Cemail_7) {
		this.Cemail_7 = Cemail_7;
	}


	public String getCemail_7() {
		return Cemail_7;
	}

	public void setCemail_6(String Cemail_6) {
		this.Cemail_6 = Cemail_6;
	}


	public String getCemail_6() {
		return Cemail_6;
	}

	public void setCfirst_6(String Cfirst_6) {
		this.Cfirst_6 = Cfirst_6;
	}


	public String getCfirst_6() {
		return Cfirst_6;
	}

	public void setCfirst_7(String Cfirst_7) {
		this.Cfirst_7 = Cfirst_7;
	}


	public String getCfirst_7() {
		return Cfirst_7;
	}

	public void setClast_6(String Clast_6) {
		this.Clast_6 = Clast_6;
	}


	public String getClast_6() {
		return Clast_6;
	}

	public void setClast_7(String Clast_7) {
		this.Clast_7 = Clast_7;
	}


	public String getClast_7() {
		return Clast_7;
	}

	public void setCcell_7(String Ccell_7) {
		this.Ccell_7 = Ccell_7;
	}


	public String getCcell_7() {
		return Ccell_7;
	}

	public void setContactpostalcode(String Contactpostalcode) {
		this.Contactpostalcode = Contactpostalcode;
	}


	public String getContactpostalcode() {
		return Contactpostalcode;
	}

	public void setAemail_7(String Aemail_7) {
		this.Aemail_7 = Aemail_7;
	}


	public String getAemail_7() {
		return Aemail_7;
	}

	public void setCellnumber_7(String Cellnumber_7) {
		this.Cellnumber_7 = Cellnumber_7;
	}


	public String getCellnumber_7() {
		return Cellnumber_7;
	}

	public void setAcomments_7(String Acomments_7) {
		this.Acomments_7 = Acomments_7;
	}


	public String getAcomments_7() {
		return Acomments_7;
	}

	public void setAcomments_6(String Acomments_6) {
		this.Acomments_6 = Acomments_6;
	}


	public String getAcomments_6() {
		return Acomments_6;
	}

	public void setBluepages_7(String Bluepages_7) {
		this.Bluepages_7 = Bluepages_7;
	}


	public String getBluepages_7() {
		return Bluepages_7;
	}

	public void setFname_7(String Fname_7) {
		this.Fname_7 = Fname_7;
	}


	public String getFname_7() {
		return Fname_7;
	}

	public void setCcity_1(String Ccity_1) {
		this.Ccity_1 = Ccity_1;
	}


	public String getCcity_1() {
		return Ccity_1;
	}

	public void setCpostal_1(String Cpostal_1) {
		this.Cpostal_1 = Cpostal_1;
	}


	public String getCpostal_1() {
		return Cpostal_1;
	}

	public void setCstate_1(String Cstate_1) {
		this.Cstate_1 = Cstate_1;
	}


	public String getCstate_1() {
		return Cstate_1;
	}

	public void setClocation_1(String Clocation_1) {
		this.Clocation_1 = Clocation_1;
	}


	public String getClocation_1() {
		return Clocation_1;
	}




}