package com.ibm.domain.core;

import javax.persistence.Id;

import javax.persistence.Column;

import javax.persistence.Entity;

import javax.persistence.GeneratedValue;

import javax.persistence.OneToMany;

import javax.persistence.Table;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

@Entity
@Table(name="Note")
 @JsonIgnoreProperties(ignoreUnknown = true)
 @JsonInclude(Include.NON_NULL)
 

@ApiModel( value = "Note", description = "note" )
public class Note  implements Serializable  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
	@Id 
 	@GeneratedValue
 	private	long Id;


	@ApiModelProperty( value = "created date", required = true )
	@Column
 	private	String Created_date;


	@ApiModelProperty( value = "created by value", required = true )
	@Column
 	private	long Created_by;


	@ApiModelProperty( value = "updated date", required = true )
	@Column
 	private	String Updated_date;


	@ApiModelProperty( value = "updated by value", required = true )
	@Column
 	private	long Updated_by;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lotusseller_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Nextsteps;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lastupdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Forecastunid;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Unid;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Dspnotepriority;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Projdur;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Createdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Pidstatus;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Lotusseller;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Dspheader;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Client;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Status;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Territory;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Notepriority;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Nextstepslast;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Engagementmanager;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Actionduedate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Project;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Br5just;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Author;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Region;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Epdesign;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactstate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Pricetype;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Dspcitystatezip;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Epplan;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Privateyn;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Bdm;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Epquestionnaire;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Actionwho;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Racompleteyn;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Prjstartdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactphone;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Elafundedyn;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Dspprivateyn;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Recentlogevent;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Auth;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Dspcitystatezip_1;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Speccustreqs;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactcity;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Logevents;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Eppricecase;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Dsptype;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Projname;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Epproposal;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Componentscomplete;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Eppresentation;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Sourcespid;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Custname;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Conexpdate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Type;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Rescount;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Br5yn;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Ssr;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Scope;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactstreetaddress;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Intlheader;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Subject;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contractreqbydate;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Summary;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactemail;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Notedocid;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Racompletedby;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Complist;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Contactname;


	@ApiModelProperty( value = "Description", required = true )
	@Column
 	private	String Br1yn;




	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}


	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}


	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}


	public long getUpdated_by() {
		return Updated_by;
	}

	public void setLotusseller_1(String Lotusseller_1) {
		this.Lotusseller_1 = Lotusseller_1;
	}


	public String getLotusseller_1() {
		return Lotusseller_1;
	}

	public void setNextsteps(String Nextsteps) {
		this.Nextsteps = Nextsteps;
	}


	public String getNextsteps() {
		return Nextsteps;
	}

	public void setLastupdate(String Lastupdate) {
		this.Lastupdate = Lastupdate;
	}


	public String getLastupdate() {
		return Lastupdate;
	}

	public void setForecastunid(String Forecastunid) {
		this.Forecastunid = Forecastunid;
	}


	public String getForecastunid() {
		return Forecastunid;
	}

	public void setUnid(String Unid) {
		this.Unid = Unid;
	}


	public String getUnid() {
		return Unid;
	}

	public void setDspnotepriority(String Dspnotepriority) {
		this.Dspnotepriority = Dspnotepriority;
	}


	public String getDspnotepriority() {
		return Dspnotepriority;
	}

	public void setProjdur(String Projdur) {
		this.Projdur = Projdur;
	}


	public String getProjdur() {
		return Projdur;
	}

	public void setCreatedate(String Createdate) {
		this.Createdate = Createdate;
	}


	public String getCreatedate() {
		return Createdate;
	}

	public void setPidstatus(String Pidstatus) {
		this.Pidstatus = Pidstatus;
	}


	public String getPidstatus() {
		return Pidstatus;
	}

	public void setLotusseller(String Lotusseller) {
		this.Lotusseller = Lotusseller;
	}


	public String getLotusseller() {
		return Lotusseller;
	}

	public void setDspheader(String Dspheader) {
		this.Dspheader = Dspheader;
	}


	public String getDspheader() {
		return Dspheader;
	}

	public void setClient(String Client) {
		this.Client = Client;
	}


	public String getClient() {
		return Client;
	}

	public void setStatus(String Status) {
		this.Status = Status;
	}


	public String getStatus() {
		return Status;
	}

	public void setTerritory(String Territory) {
		this.Territory = Territory;
	}


	public String getTerritory() {
		return Territory;
	}

	public void setNotepriority(String Notepriority) {
		this.Notepriority = Notepriority;
	}


	public String getNotepriority() {
		return Notepriority;
	}

	public void setNextstepslast(String Nextstepslast) {
		this.Nextstepslast = Nextstepslast;
	}


	public String getNextstepslast() {
		return Nextstepslast;
	}

	public void setEngagementmanager(String Engagementmanager) {
		this.Engagementmanager = Engagementmanager;
	}


	public String getEngagementmanager() {
		return Engagementmanager;
	}

	public void setActionduedate(String Actionduedate) {
		this.Actionduedate = Actionduedate;
	}


	public String getActionduedate() {
		return Actionduedate;
	}

	public void setProject(String Project) {
		this.Project = Project;
	}


	public String getProject() {
		return Project;
	}

	public void setBr5just(String Br5just) {
		this.Br5just = Br5just;
	}


	public String getBr5just() {
		return Br5just;
	}

	public void setAuthor(String Author) {
		this.Author = Author;
	}


	public String getAuthor() {
		return Author;
	}

	public void setRegion(String Region) {
		this.Region = Region;
	}


	public String getRegion() {
		return Region;
	}

	public void setEpdesign(String Epdesign) {
		this.Epdesign = Epdesign;
	}


	public String getEpdesign() {
		return Epdesign;
	}

	public void setContactstate(String Contactstate) {
		this.Contactstate = Contactstate;
	}


	public String getContactstate() {
		return Contactstate;
	}

	public void setPricetype(String Pricetype) {
		this.Pricetype = Pricetype;
	}


	public String getPricetype() {
		return Pricetype;
	}

	public void setDspcitystatezip(String Dspcitystatezip) {
		this.Dspcitystatezip = Dspcitystatezip;
	}


	public String getDspcitystatezip() {
		return Dspcitystatezip;
	}

	public void setEpplan(String Epplan) {
		this.Epplan = Epplan;
	}


	public String getEpplan() {
		return Epplan;
	}

	public void setPrivateyn(String Privateyn) {
		this.Privateyn = Privateyn;
	}


	public String getPrivateyn() {
		return Privateyn;
	}

	public void setBdm(String Bdm) {
		this.Bdm = Bdm;
	}


	public String getBdm() {
		return Bdm;
	}

	public void setEpquestionnaire(String Epquestionnaire) {
		this.Epquestionnaire = Epquestionnaire;
	}


	public String getEpquestionnaire() {
		return Epquestionnaire;
	}

	public void setActionwho(String Actionwho) {
		this.Actionwho = Actionwho;
	}


	public String getActionwho() {
		return Actionwho;
	}

	public void setRacompleteyn(String Racompleteyn) {
		this.Racompleteyn = Racompleteyn;
	}


	public String getRacompleteyn() {
		return Racompleteyn;
	}

	public void setPrjstartdate(String Prjstartdate) {
		this.Prjstartdate = Prjstartdate;
	}


	public String getPrjstartdate() {
		return Prjstartdate;
	}

	public void setContactphone(String Contactphone) {
		this.Contactphone = Contactphone;
	}


	public String getContactphone() {
		return Contactphone;
	}

	public void setElafundedyn(String Elafundedyn) {
		this.Elafundedyn = Elafundedyn;
	}


	public String getElafundedyn() {
		return Elafundedyn;
	}

	public void setDspprivateyn(String Dspprivateyn) {
		this.Dspprivateyn = Dspprivateyn;
	}


	public String getDspprivateyn() {
		return Dspprivateyn;
	}

	public void setRecentlogevent(String Recentlogevent) {
		this.Recentlogevent = Recentlogevent;
	}


	public String getRecentlogevent() {
		return Recentlogevent;
	}

	public void setAuth(String Auth) {
		this.Auth = Auth;
	}


	public String getAuth() {
		return Auth;
	}

	public void setDspcitystatezip_1(String Dspcitystatezip_1) {
		this.Dspcitystatezip_1 = Dspcitystatezip_1;
	}


	public String getDspcitystatezip_1() {
		return Dspcitystatezip_1;
	}

	public void setSpeccustreqs(String Speccustreqs) {
		this.Speccustreqs = Speccustreqs;
	}


	public String getSpeccustreqs() {
		return Speccustreqs;
	}

	public void setContactcity(String Contactcity) {
		this.Contactcity = Contactcity;
	}


	public String getContactcity() {
		return Contactcity;
	}

	public void setLogevents(String Logevents) {
		this.Logevents = Logevents;
	}


	public String getLogevents() {
		return Logevents;
	}

	public void setEppricecase(String Eppricecase) {
		this.Eppricecase = Eppricecase;
	}


	public String getEppricecase() {
		return Eppricecase;
	}

	public void setDsptype(String Dsptype) {
		this.Dsptype = Dsptype;
	}


	public String getDsptype() {
		return Dsptype;
	}

	public void setProjname(String Projname) {
		this.Projname = Projname;
	}


	public String getProjname() {
		return Projname;
	}

	public void setEpproposal(String Epproposal) {
		this.Epproposal = Epproposal;
	}


	public String getEpproposal() {
		return Epproposal;
	}

	public void setComponentscomplete(String Componentscomplete) {
		this.Componentscomplete = Componentscomplete;
	}


	public String getComponentscomplete() {
		return Componentscomplete;
	}

	public void setEppresentation(String Eppresentation) {
		this.Eppresentation = Eppresentation;
	}


	public String getEppresentation() {
		return Eppresentation;
	}

	public void setSourcespid(String Sourcespid) {
		this.Sourcespid = Sourcespid;
	}


	public String getSourcespid() {
		return Sourcespid;
	}

	public void setCustname(String Custname) {
		this.Custname = Custname;
	}


	public String getCustname() {
		return Custname;
	}

	public void setConexpdate(String Conexpdate) {
		this.Conexpdate = Conexpdate;
	}


	public String getConexpdate() {
		return Conexpdate;
	}

	public void setType(String Type) {
		this.Type = Type;
	}


	public String getType() {
		return Type;
	}

	public void setRescount(String Rescount) {
		this.Rescount = Rescount;
	}


	public String getRescount() {
		return Rescount;
	}

	public void setBr5yn(String Br5yn) {
		this.Br5yn = Br5yn;
	}


	public String getBr5yn() {
		return Br5yn;
	}

	public void setSsr(String Ssr) {
		this.Ssr = Ssr;
	}


	public String getSsr() {
		return Ssr;
	}

	public void setScope(String Scope) {
		this.Scope = Scope;
	}


	public String getScope() {
		return Scope;
	}

	public void setContactstreetaddress(String Contactstreetaddress) {
		this.Contactstreetaddress = Contactstreetaddress;
	}


	public String getContactstreetaddress() {
		return Contactstreetaddress;
	}

	public void setIntlheader(String Intlheader) {
		this.Intlheader = Intlheader;
	}


	public String getIntlheader() {
		return Intlheader;
	}

	public void setSubject(String Subject) {
		this.Subject = Subject;
	}


	public String getSubject() {
		return Subject;
	}

	public void setContractreqbydate(String Contractreqbydate) {
		this.Contractreqbydate = Contractreqbydate;
	}


	public String getContractreqbydate() {
		return Contractreqbydate;
	}

	public void setSummary(String Summary) {
		this.Summary = Summary;
	}


	public String getSummary() {
		return Summary;
	}

	public void setContactemail(String Contactemail) {
		this.Contactemail = Contactemail;
	}


	public String getContactemail() {
		return Contactemail;
	}

	public void setNotedocid(String Notedocid) {
		this.Notedocid = Notedocid;
	}


	public String getNotedocid() {
		return Notedocid;
	}

	public void setRacompletedby(String Racompletedby) {
		this.Racompletedby = Racompletedby;
	}


	public String getRacompletedby() {
		return Racompletedby;
	}

	public void setComplist(String Complist) {
		this.Complist = Complist;
	}


	public String getComplist() {
		return Complist;
	}

	public void setContactname(String Contactname) {
		this.Contactname = Contactname;
	}


	public String getContactname() {
		return Contactname;
	}

	public void setBr1yn(String Br1yn) {
		this.Br1yn = Br1yn;
	}


	public String getBr1yn() {
		return Br1yn;
	}




}