server:
  port: 8080




#Database
db:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://mydb:3306/ibmsalesforecast?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: tang3456

#Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update


security:
  basic:
    enabled: false

entitymanager:
  packagesToScan: com.ibm.*


