package com.ibm.dao.mysql;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.Column;
import javax.persistence.Query;
import javax.persistence.Transient;
import javax.sound.midi.SysexMessage;
import javax.sql.DataSource;
import javax.transaction.Transactional;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnitUtil;
import javax.transaction.Transactional;
import javax.persistence.Query;


import javax.annotation.Resource;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.apache.log4j.*;



import com.ibm.domain.core.AVPLeadSource;
import com.ibm.domain.core.IBUser;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Transactional
@Repository("AVPLeadSource_Default_ActivityDao")
public class AVPLeadSource_Default_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(AVPLeadSource_Default_ActivityDao.class.getName());

	@Value("${create_AVPLeadSource.sql}")
	private String create_AVPLeadSource;
	@Value("${search_for_update_AVPLeadSource.sql}")
	private String search_for_update_AVPLeadSource;
	@Value("${update_AVPLeadSource.sql}")
	private String update_AVPLeadSource;
	@Value("${delete_AVPLeadSource.sql}")
	private String delete_AVPLeadSource;
	@Value("${get_all_AVPLeadSource.sql}")
	private String get_all_AVPLeadSource;


    @PersistenceContext
	private EntityManager entityManager;



	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  AVPLeadSource noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_AVPLeadSource object will return
	*@throws Exception
	*/

	public AVPLeadSource avpleadsource_search_for_update(long id, IBUser user) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("avpleadsource_search_for_update Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(search_for_update_AVPLeadSource,AVPLeadSource.class)

			.setParameter("id", id);;

			ArrayList<AVPLeadSource> AVPLeadSource_list =	(ArrayList<AVPLeadSource>)result.getResultList();

			if(AVPLeadSource_list  == null){

			log.error("avpleadsource_search_for_update Dao throws exception :" + "no AVPLeadSource found" );
			throw new Exception("no AVPLeadSource found");
			}
			log.info("Object returned from avpleadsource_search_for_update  Dao method !");
			return (AVPLeadSource) AVPLeadSource_list.get(0);

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("avpleadsource_search_for_update Dao throws exception : "+e.toString());

		}
		return null;


	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  AVPLeadSource noun from  database
	*
	*
	*@return List of AVPLeadSource object will return
	*@throws Exception
	*/

	public ArrayList<AVPLeadSource> get_all_avpleadsource() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_avpleadsource Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(get_all_AVPLeadSource,AVPLeadSource.class)

;

			ArrayList<AVPLeadSource> AVPLeadSource_list =	(ArrayList<AVPLeadSource>)result.getResultList();

			if(AVPLeadSource_list .size() < 1){

			log.error("get_all_avpleadsource Dao throws exception :" + "no AVPLeadSource found" );
			throw new Exception("no AVPLeadSource found");
			}
			log.info("Object returned from get_all_avpleadsource  Dao method !");
			return (ArrayList<AVPLeadSource>) AVPLeadSource_list;

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("get_all_avpleadsource Dao throws exception : "+e.toString());

		}
		return null;


	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  AVPLeadSource noun into database
	*@param AVPLeadSource
	*@param user
	*@return AVPLeadSource object will return
	*@throws Exception
	*/

	@Transactional
	public AVPLeadSource create_avpleadsource(AVPLeadSource AVPLeadSource, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_avpleadsource Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(create_AVPLeadSource)
			.setParameter("avpleadsource", AVPLeadSource.getAvpleadsource())
			.setParameter("description", AVPLeadSource.getDescription())
			.setParameter("created_by", user == null ? 0:user.getId())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			int insertedId = query.executeUpdate();
					String lastIndex="select last_insert_id()";
					Query sql = entityManager.createNativeQuery(lastIndex);
					BigInteger new_id = (BigInteger) sql.getSingleResult();
					AVPLeadSource.setId(new_id.longValue());
					System.out.println("create data---"+insertedId);

			log.info("Object returned from create_avpleadsource  Dao method !");

			return AVPLeadSource;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (create_avpleadsource) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  AVPLeadSource noun into database
	*@param AVPLeadSource
	*@param user
	*@return the_AVPLeadSource object will return
	*@throws Exception
	*/

	@Transactional
	public AVPLeadSource update_avpleadsource(AVPLeadSource AVPLeadSource, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_avpleadsource Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(update_AVPLeadSource)
			.setParameter("id", AVPLeadSource.getId())
			.setParameter("avpleadsource", AVPLeadSource.getAvpleadsource())
			.setParameter("description", AVPLeadSource.getDescription())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			query.executeUpdate();

			log.info("Object returned from update_avpleadsource  Dao method !");

			return AVPLeadSource;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (update_avpleadsource) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  AVPLeadSource noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_AVPLeadSource id deleted based on id
	*@throws Exception
	*/

	@Transactional
	public String  delete_avpleadsource(long id, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_avpleadsource Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(delete_AVPLeadSource)
			.setParameter("id", id);

			query.executeUpdate();

			log.info("Object returned from delete_avpleadsource  Dao method !");

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (delete_avpleadsource) throws Exception : "+e.toString());

		}
		return null;



	}



}