package com.ibm.dao.mysql;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.Column;
import javax.persistence.Query;
import javax.persistence.Transient;
import javax.sound.midi.SysexMessage;
import javax.sql.DataSource;
import javax.transaction.Transactional;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnitUtil;
import javax.transaction.Transactional;
import javax.persistence.Query;


import javax.annotation.Resource;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.apache.log4j.*;



import com.ibm.domain.core.Client;
import com.ibm.domain.core.IBUser;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Transactional
@Repository("Client_Default_ActivityDao")
public class Client_Default_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Client_Default_ActivityDao.class.getName());

	@Value("${create_Client.sql}")
	private String create_Client;
	@Value("${search_for_update_Client.sql}")
	private String search_for_update_Client;
	@Value("${update_Client.sql}")
	private String update_Client;
	@Value("${delete_Client.sql}")
	private String delete_Client;
	@Value("${get_all_Client.sql}")
	private String get_all_Client;
	@Value("${search_for_detail_Client.sql}")
	private String search_for_detail_Client;


    @PersistenceContext
	private EntityManager entityManager;



	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Client noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Client object will return
	*@throws Exception
	*/

	public Client client_search_for_update(long id, IBUser user) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("client_search_for_update Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(search_for_update_Client,Client.class)

			.setParameter("id", id);;

			ArrayList<Client> Client_list =	(ArrayList<Client>)result.getResultList();

			if(Client_list  == null){

			log.error("client_search_for_update Dao throws exception :" + "no Client found" );
			throw new Exception("no Client found");
			}
			log.info("Object returned from client_search_for_update  Dao method !");
			return (Client) Client_list.get(0);

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("client_search_for_update Dao throws exception : "+e.toString());

		}
		return null;


	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Client noun from  database
	*
	*
	*@return List of Client object will return
	*@throws Exception
	*/

	public ArrayList<Client> get_all_client() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_client Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(get_all_Client,Client.class)

;

			ArrayList<Client> Client_list =	(ArrayList<Client>)result.getResultList();

			if(Client_list .size() < 1){

			log.error("get_all_client Dao throws exception :" + "no Client found" );
			throw new Exception("no Client found");
			}
			log.info("Object returned from get_all_client  Dao method !");
			return (ArrayList<Client>) Client_list;

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("get_all_client Dao throws exception : "+e.toString());

		}
		return null;


	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Client noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Client object will return
	*@throws Exception
	*/

	public Client client_search_for_detail(long id, IBUser user) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("client_search_for_detail Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(search_for_detail_Client,Client.class)

			.setParameter("id", id);;

			ArrayList<Client> Client_list =	(ArrayList<Client>)result.getResultList();

			if(Client_list  == null){

			log.error("client_search_for_detail Dao throws exception :" + "no Client found" );
			throw new Exception("no Client found");
			}
			log.info("Object returned from client_search_for_detail  Dao method !");
			return (Client) Client_list.get(0);

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("client_search_for_detail Dao throws exception : "+e.toString());

		}
		return null;


	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Client noun into database
	*@param Client
	*@param user
	*@return Client object will return
	*@throws Exception
	*/

	@Transactional
	public Client create_client(Client Client, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_client Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(create_Client)
			.setParameter("clientname", Client.getClientname())
			.setParameter("addressone", Client.getAddressone())
			.setParameter("addresstwo", Client.getAddresstwo())
			.setParameter("city", Client.getCity())
			.setParameter("stateorprovince", Client.getStateorprovince())
			.setParameter("postalcode", Client.getPostalcode())
			.setParameter("country", Client.getCountry())
			.setParameter("primarycontactname", Client.getPrimarycontactname())
			.setParameter("primarycontactnamephone", Client.getPrimarycontactnamephone())
			.setParameter("primarycontactemail", Client.getPrimarycontactemail())
			.setParameter("notes", Client.getNotes())
			.setParameter("created_by", user == null ? 0:user.getId())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			int insertedId = query.executeUpdate();
					String lastIndex="select last_insert_id()";
					Query sql = entityManager.createNativeQuery(lastIndex);
					BigInteger new_id = (BigInteger) sql.getSingleResult();
					Client.setId(new_id.longValue());
					System.out.println("create data---"+insertedId);

			log.info("Object returned from create_client  Dao method !");

			return Client;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (create_client) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Client noun into database
	*@param Client
	*@param user
	*@return the_Client object will return
	*@throws Exception
	*/

	@Transactional
	public Client update_client(Client Client, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_client Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(update_Client)
			.setParameter("id", Client.getId())
			.setParameter("clientname", Client.getClientname())
			.setParameter("addressone", Client.getAddressone())
			.setParameter("addresstwo", Client.getAddresstwo())
			.setParameter("city", Client.getCity())
			.setParameter("stateorprovince", Client.getStateorprovince())
			.setParameter("postalcode", Client.getPostalcode())
			.setParameter("country", Client.getCountry())
			.setParameter("primarycontactname", Client.getPrimarycontactname())
			.setParameter("primarycontactnamephone", Client.getPrimarycontactnamephone())
			.setParameter("primarycontactemail", Client.getPrimarycontactemail())
			.setParameter("notes", Client.getNotes())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			query.executeUpdate();

			log.info("Object returned from update_client  Dao method !");

			return Client;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (update_client) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Client noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Client id deleted based on id
	*@throws Exception
	*/

	@Transactional
	public String  delete_client(long id, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_client Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(delete_Client)
			.setParameter("id", id);

			query.executeUpdate();

			log.info("Object returned from delete_client  Dao method !");

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (delete_client) throws Exception : "+e.toString());

		}
		return null;



	}



}