package com.ibm.dao.mysql;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.Column;
import javax.persistence.Query;
import javax.persistence.Transient;
import javax.sound.midi.SysexMessage;
import javax.sql.DataSource;
import javax.transaction.Transactional;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnitUtil;
import javax.transaction.Transactional;
import javax.persistence.Query;


import javax.annotation.Resource;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.apache.log4j.*;



import com.ibm.domain.core.MonthEnd;
import com.ibm.domain.core.IBUser;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Transactional
@Repository("MonthEnd_Default_ActivityDao")
public class MonthEnd_Default_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(MonthEnd_Default_ActivityDao.class.getName());

	@Value("${create_MonthEnd.sql}")
	private String create_MonthEnd;
	@Value("${search_for_update_MonthEnd.sql}")
	private String search_for_update_MonthEnd;
	@Value("${update_MonthEnd.sql}")
	private String update_MonthEnd;
	@Value("${delete_MonthEnd.sql}")
	private String delete_MonthEnd;
	@Value("${get_all_MonthEnd.sql}")
	private String get_all_MonthEnd;


    @PersistenceContext
	private EntityManager entityManager;



	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  MonthEnd noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_MonthEnd object will return
	*@throws Exception
	*/

	public MonthEnd monthend_search_for_update(long id, IBUser user) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("monthend_search_for_update Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(search_for_update_MonthEnd,MonthEnd.class)

			.setParameter("id", id);;

			ArrayList<MonthEnd> MonthEnd_list =	(ArrayList<MonthEnd>)result.getResultList();

			if(MonthEnd_list  == null){

			log.error("monthend_search_for_update Dao throws exception :" + "no MonthEnd found" );
			throw new Exception("no MonthEnd found");
			}
			log.info("Object returned from monthend_search_for_update  Dao method !");
			return (MonthEnd) MonthEnd_list.get(0);

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("monthend_search_for_update Dao throws exception : "+e.toString());

		}
		return null;


	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  MonthEnd noun from  database
	*
	*
	*@return List of MonthEnd object will return
	*@throws Exception
	*/

	public ArrayList<MonthEnd> get_all_monthend() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_monthend Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(get_all_MonthEnd,MonthEnd.class)

;

			ArrayList<MonthEnd> MonthEnd_list =	(ArrayList<MonthEnd>)result.getResultList();

			if(MonthEnd_list .size() < 1){

			log.error("get_all_monthend Dao throws exception :" + "no MonthEnd found" );
			throw new Exception("no MonthEnd found");
			}
			log.info("Object returned from get_all_monthend  Dao method !");
			return (ArrayList<MonthEnd>) MonthEnd_list;

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("get_all_monthend Dao throws exception : "+e.toString());

		}
		return null;


	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  MonthEnd noun into database
	*@param MonthEnd
	*@param user
	*@return MonthEnd object will return
	*@throws Exception
	*/

	@Transactional
	public MonthEnd create_monthend(MonthEnd MonthEnd, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_monthend Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(create_MonthEnd)
			.setParameter("monthend", MonthEnd.getMonthend())
			.setParameter("description", MonthEnd.getDescription())
			.setParameter("created_by", user == null ? 0:user.getId())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			int insertedId = query.executeUpdate();
					String lastIndex="select last_insert_id()";
					Query sql = entityManager.createNativeQuery(lastIndex);
					BigInteger new_id = (BigInteger) sql.getSingleResult();
					MonthEnd.setId(new_id.longValue());
					System.out.println("create data---"+insertedId);

			log.info("Object returned from create_monthend  Dao method !");

			return MonthEnd;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (create_monthend) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  MonthEnd noun into database
	*@param MonthEnd
	*@param user
	*@return the_MonthEnd object will return
	*@throws Exception
	*/

	@Transactional
	public MonthEnd update_monthend(MonthEnd MonthEnd, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_monthend Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(update_MonthEnd)
			.setParameter("id", MonthEnd.getId())
			.setParameter("monthend", MonthEnd.getMonthend())
			.setParameter("description", MonthEnd.getDescription())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			query.executeUpdate();

			log.info("Object returned from update_monthend  Dao method !");

			return MonthEnd;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (update_monthend) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  MonthEnd noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_MonthEnd id deleted based on id
	*@throws Exception
	*/

	@Transactional
	public String  delete_monthend(long id, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_monthend Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(delete_MonthEnd)
			.setParameter("id", id);

			query.executeUpdate();

			log.info("Object returned from delete_monthend  Dao method !");

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (delete_monthend) throws Exception : "+e.toString());

		}
		return null;



	}



}