package com.ibm.dao.mysql;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.Column;
import javax.persistence.Query;
import javax.persistence.Transient;
import javax.sound.midi.SysexMessage;
import javax.sql.DataSource;
import javax.transaction.Transactional;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnitUtil;
import javax.transaction.Transactional;
import javax.persistence.Query;


import javax.annotation.Resource;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.apache.log4j.*;



import com.ibm.domain.core.Offering;
import com.ibm.domain.core.IBUser;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Transactional
@Repository("Offering_Default_ActivityDao")
public class Offering_Default_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Offering_Default_ActivityDao.class.getName());

	@Value("${create_Offering.sql}")
	private String create_Offering;
	@Value("${search_for_update_Offering.sql}")
	private String search_for_update_Offering;
	@Value("${update_Offering.sql}")
	private String update_Offering;
	@Value("${delete_Offering.sql}")
	private String delete_Offering;
	@Value("${get_all_Offering.sql}")
	private String get_all_Offering;


    @PersistenceContext
	private EntityManager entityManager;



	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Offering noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Offering object will return
	*@throws Exception
	*/

	public Offering offering_search_for_update(long id, IBUser user) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("offering_search_for_update Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(search_for_update_Offering,Offering.class)

			.setParameter("id", id);;

			ArrayList<Offering> Offering_list =	(ArrayList<Offering>)result.getResultList();

			if(Offering_list  == null){

			log.error("offering_search_for_update Dao throws exception :" + "no Offering found" );
			throw new Exception("no Offering found");
			}
			log.info("Object returned from offering_search_for_update  Dao method !");
			return (Offering) Offering_list.get(0);

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("offering_search_for_update Dao throws exception : "+e.toString());

		}
		return null;


	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Offering noun from  database
	*
	*
	*@return List of Offering object will return
	*@throws Exception
	*/

	public ArrayList<Offering> get_all_offering() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_offering Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(get_all_Offering,Offering.class)

;

			ArrayList<Offering> Offering_list =	(ArrayList<Offering>)result.getResultList();

			if(Offering_list .size() < 1){

			log.error("get_all_offering Dao throws exception :" + "no Offering found" );
			throw new Exception("no Offering found");
			}
			log.info("Object returned from get_all_offering  Dao method !");
			return (ArrayList<Offering>) Offering_list;

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("get_all_offering Dao throws exception : "+e.toString());

		}
		return null;


	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Offering noun into database
	*@param Offering
	*@param user
	*@return Offering object will return
	*@throws Exception
	*/

	@Transactional
	public Offering create_offering(Offering Offering, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_offering Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(create_Offering)
			.setParameter("offering", Offering.getOffering())
			.setParameter("description", Offering.getDescription())
			.setParameter("created_by", user == null ? 0:user.getId())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			int insertedId = query.executeUpdate();
					String lastIndex="select last_insert_id()";
					Query sql = entityManager.createNativeQuery(lastIndex);
					BigInteger new_id = (BigInteger) sql.getSingleResult();
					Offering.setId(new_id.longValue());
					System.out.println("create data---"+insertedId);

			log.info("Object returned from create_offering  Dao method !");

			return Offering;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (create_offering) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Offering noun into database
	*@param Offering
	*@param user
	*@return the_Offering object will return
	*@throws Exception
	*/

	@Transactional
	public Offering update_offering(Offering Offering, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_offering Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(update_Offering)
			.setParameter("id", Offering.getId())
			.setParameter("offering", Offering.getOffering())
			.setParameter("description", Offering.getDescription())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			query.executeUpdate();

			log.info("Object returned from update_offering  Dao method !");

			return Offering;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (update_offering) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Offering noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Offering id deleted based on id
	*@throws Exception
	*/

	@Transactional
	public String  delete_offering(long id, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_offering Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(delete_Offering)
			.setParameter("id", id);

			query.executeUpdate();

			log.info("Object returned from delete_offering  Dao method !");

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (delete_offering) throws Exception : "+e.toString());

		}
		return null;



	}



}