package com.ibm.dao.mysql;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.Column;
import javax.persistence.Query;
import javax.persistence.Transient;
import javax.sound.midi.SysexMessage;
import javax.sql.DataSource;
import javax.transaction.Transactional;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnitUtil;
import javax.transaction.Transactional;
import javax.persistence.Query;


import javax.annotation.Resource;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.apache.log4j.*;



import com.ibm.domain.core.Partners;
import com.ibm.domain.core.IBUser;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Transactional
@Repository("Partners_Default_ActivityDao")
public class Partners_Default_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Partners_Default_ActivityDao.class.getName());

	@Value("${create_Partners.sql}")
	private String create_Partners;
	@Value("${search_for_update_Partners.sql}")
	private String search_for_update_Partners;
	@Value("${update_Partners.sql}")
	private String update_Partners;
	@Value("${delete_Partners.sql}")
	private String delete_Partners;
	@Value("${get_all_Partners.sql}")
	private String get_all_Partners;


    @PersistenceContext
	private EntityManager entityManager;



	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Partners noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Partners object will return
	*@throws Exception
	*/

	public Partners partners_search_for_update(long id, IBUser user) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("partners_search_for_update Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(search_for_update_Partners,Partners.class)

			.setParameter("id", id);;

			ArrayList<Partners> Partners_list =	(ArrayList<Partners>)result.getResultList();

			if(Partners_list  == null){

			log.error("partners_search_for_update Dao throws exception :" + "no Partners found" );
			throw new Exception("no Partners found");
			}
			log.info("Object returned from partners_search_for_update  Dao method !");
			return (Partners) Partners_list.get(0);

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("partners_search_for_update Dao throws exception : "+e.toString());

		}
		return null;


	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Partners noun from  database
	*
	*
	*@return List of Partners object will return
	*@throws Exception
	*/

	public ArrayList<Partners> get_all_partners() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_partners Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(get_all_Partners,Partners.class)

;

			ArrayList<Partners> Partners_list =	(ArrayList<Partners>)result.getResultList();

			if(Partners_list .size() < 1){

			log.error("get_all_partners Dao throws exception :" + "no Partners found" );
			throw new Exception("no Partners found");
			}
			log.info("Object returned from get_all_partners  Dao method !");
			return (ArrayList<Partners>) Partners_list;

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("get_all_partners Dao throws exception : "+e.toString());

		}
		return null;


	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Partners noun into database
	*@param Partners
	*@param user
	*@return Partners object will return
	*@throws Exception
	*/

	@Transactional
	public Partners create_partners(Partners Partners, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_partners Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(create_Partners)
			.setParameter("partners", Partners.getPartners())
			.setParameter("description", Partners.getDescription())
			.setParameter("created_by", user == null ? 0:user.getId())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			int insertedId = query.executeUpdate();
					String lastIndex="select last_insert_id()";
					Query sql = entityManager.createNativeQuery(lastIndex);
					BigInteger new_id = (BigInteger) sql.getSingleResult();
					Partners.setId(new_id.longValue());
					System.out.println("create data---"+insertedId);

			log.info("Object returned from create_partners  Dao method !");

			return Partners;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (create_partners) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Partners noun into database
	*@param Partners
	*@param user
	*@return the_Partners object will return
	*@throws Exception
	*/

	@Transactional
	public Partners update_partners(Partners Partners, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_partners Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(update_Partners)
			.setParameter("id", Partners.getId())
			.setParameter("partners", Partners.getPartners())
			.setParameter("description", Partners.getDescription())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			query.executeUpdate();

			log.info("Object returned from update_partners  Dao method !");

			return Partners;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (update_partners) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Partners noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Partners id deleted based on id
	*@throws Exception
	*/

	@Transactional
	public String  delete_partners(long id, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_partners Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(delete_Partners)
			.setParameter("id", id);

			query.executeUpdate();

			log.info("Object returned from delete_partners  Dao method !");

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (delete_partners) throws Exception : "+e.toString());

		}
		return null;



	}



}