package com.ibm.dao.mysql;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.Column;
import javax.persistence.Query;
import javax.persistence.Transient;
import javax.sound.midi.SysexMessage;
import javax.sql.DataSource;
import javax.transaction.Transactional;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnitUtil;
import javax.transaction.Transactional;
import javax.persistence.Query;


import javax.annotation.Resource;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.apache.log4j.*;



import com.ibm.domain.core.Percentage;
import com.ibm.domain.core.IBUser;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Transactional
@Repository("Percentage_Default_ActivityDao")
public class Percentage_Default_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Percentage_Default_ActivityDao.class.getName());

	@Value("${create_Percentage.sql}")
	private String create_Percentage;
	@Value("${search_for_update_Percentage.sql}")
	private String search_for_update_Percentage;
	@Value("${update_Percentage.sql}")
	private String update_Percentage;
	@Value("${delete_Percentage.sql}")
	private String delete_Percentage;
	@Value("${get_all_Percentage.sql}")
	private String get_all_Percentage;


    @PersistenceContext
	private EntityManager entityManager;



	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Percentage noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Percentage object will return
	*@throws Exception
	*/

	public Percentage percentage_search_for_update(long id, IBUser user) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("percentage_search_for_update Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(search_for_update_Percentage,Percentage.class)

			.setParameter("id", id);;

			ArrayList<Percentage> Percentage_list =	(ArrayList<Percentage>)result.getResultList();

			if(Percentage_list  == null){

			log.error("percentage_search_for_update Dao throws exception :" + "no Percentage found" );
			throw new Exception("no Percentage found");
			}
			log.info("Object returned from percentage_search_for_update  Dao method !");
			return (Percentage) Percentage_list.get(0);

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("percentage_search_for_update Dao throws exception : "+e.toString());

		}
		return null;


	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Percentage noun from  database
	*
	*
	*@return List of Percentage object will return
	*@throws Exception
	*/

	public ArrayList<Percentage> get_all_percentage() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_percentage Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(get_all_Percentage,Percentage.class)

;

			ArrayList<Percentage> Percentage_list =	(ArrayList<Percentage>)result.getResultList();

			if(Percentage_list .size() < 1){

			log.error("get_all_percentage Dao throws exception :" + "no Percentage found" );
			throw new Exception("no Percentage found");
			}
			log.info("Object returned from get_all_percentage  Dao method !");
			return (ArrayList<Percentage>) Percentage_list;

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("get_all_percentage Dao throws exception : "+e.toString());

		}
		return null;


	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Percentage noun into database
	*@param Percentage
	*@param user
	*@return Percentage object will return
	*@throws Exception
	*/

	@Transactional
	public Percentage create_percentage(Percentage Percentage, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_percentage Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(create_Percentage)
			.setParameter("percentage", Percentage.getPercentage())
			.setParameter("description", Percentage.getDescription())
			.setParameter("created_by", user == null ? 0:user.getId())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			int insertedId = query.executeUpdate();
					String lastIndex="select last_insert_id()";
					Query sql = entityManager.createNativeQuery(lastIndex);
					BigInteger new_id = (BigInteger) sql.getSingleResult();
					Percentage.setId(new_id.longValue());
					System.out.println("create data---"+insertedId);

			log.info("Object returned from create_percentage  Dao method !");

			return Percentage;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (create_percentage) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Percentage noun into database
	*@param Percentage
	*@param user
	*@return the_Percentage object will return
	*@throws Exception
	*/

	@Transactional
	public Percentage update_percentage(Percentage Percentage, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_percentage Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(update_Percentage)
			.setParameter("id", Percentage.getId())
			.setParameter("percentage", Percentage.getPercentage())
			.setParameter("description", Percentage.getDescription())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			query.executeUpdate();

			log.info("Object returned from update_percentage  Dao method !");

			return Percentage;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (update_percentage) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Percentage noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Percentage id deleted based on id
	*@throws Exception
	*/

	@Transactional
	public String  delete_percentage(long id, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_percentage Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(delete_Percentage)
			.setParameter("id", id);

			query.executeUpdate();

			log.info("Object returned from delete_percentage  Dao method !");

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (delete_percentage) throws Exception : "+e.toString());

		}
		return null;



	}



}