package com.ibm.dao.mysql;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.Column;
import javax.persistence.Query;
import javax.persistence.Transient;
import javax.sound.midi.SysexMessage;
import javax.sql.DataSource;
import javax.transaction.Transactional;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnitUtil;
import javax.transaction.Transactional;
import javax.persistence.Query;


import javax.annotation.Resource;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.apache.log4j.*;



import com.ibm.domain.core.Region;
import com.ibm.domain.core.IBUser;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Transactional
@Repository("Region_Default_ActivityDao")
public class Region_Default_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Region_Default_ActivityDao.class.getName());

	@Value("${create_Region.sql}")
	private String create_Region;
	@Value("${search_for_update_Region.sql}")
	private String search_for_update_Region;
	@Value("${update_Region.sql}")
	private String update_Region;
	@Value("${delete_Region.sql}")
	private String delete_Region;
	@Value("${get_all_Region.sql}")
	private String get_all_Region;


    @PersistenceContext
	private EntityManager entityManager;



	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Region noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Region object will return
	*@throws Exception
	*/

	public Region region_search_for_update(long id, IBUser user) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("region_search_for_update Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(search_for_update_Region,Region.class)

			.setParameter("id", id);;

			ArrayList<Region> Region_list =	(ArrayList<Region>)result.getResultList();

			if(Region_list  == null){

			log.error("region_search_for_update Dao throws exception :" + "no Region found" );
			throw new Exception("no Region found");
			}
			log.info("Object returned from region_search_for_update  Dao method !");
			return (Region) Region_list.get(0);

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("region_search_for_update Dao throws exception : "+e.toString());

		}
		return null;


	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Region noun from  database
	*
	*
	*@return List of Region object will return
	*@throws Exception
	*/

	public ArrayList<Region> get_all_region() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_region Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(get_all_Region,Region.class)

;

			ArrayList<Region> Region_list =	(ArrayList<Region>)result.getResultList();

			if(Region_list .size() < 1){

			log.error("get_all_region Dao throws exception :" + "no Region found" );
			throw new Exception("no Region found");
			}
			log.info("Object returned from get_all_region  Dao method !");
			return (ArrayList<Region>) Region_list;

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("get_all_region Dao throws exception : "+e.toString());

		}
		return null;


	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Region noun into database
	*@param Region
	*@param user
	*@return Region object will return
	*@throws Exception
	*/

	@Transactional
	public Region create_region(Region Region, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_region Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(create_Region)
			.setParameter("region", Region.getRegion())
			.setParameter("description", Region.getDescription())
			.setParameter("created_by", user == null ? 0:user.getId())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			int insertedId = query.executeUpdate();
					String lastIndex="select last_insert_id()";
					Query sql = entityManager.createNativeQuery(lastIndex);
					BigInteger new_id = (BigInteger) sql.getSingleResult();
					Region.setId(new_id.longValue());
					System.out.println("create data---"+insertedId);

			log.info("Object returned from create_region  Dao method !");

			return Region;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (create_region) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Region noun into database
	*@param Region
	*@param user
	*@return the_Region object will return
	*@throws Exception
	*/

	@Transactional
	public Region update_region(Region Region, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_region Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(update_Region)
			.setParameter("id", Region.getId())
			.setParameter("region", Region.getRegion())
			.setParameter("description", Region.getDescription())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			query.executeUpdate();

			log.info("Object returned from update_region  Dao method !");

			return Region;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (update_region) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Region noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Region id deleted based on id
	*@throws Exception
	*/

	@Transactional
	public String  delete_region(long id, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_region Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(delete_Region)
			.setParameter("id", id);

			query.executeUpdate();

			log.info("Object returned from delete_region  Dao method !");

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (delete_region) throws Exception : "+e.toString());

		}
		return null;



	}



}