package com.ibm.dao.mysql;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.Column;
import javax.persistence.Query;
import javax.persistence.Transient;
import javax.sound.midi.SysexMessage;
import javax.sql.DataSource;
import javax.transaction.Transactional;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnitUtil;
import javax.transaction.Transactional;
import javax.persistence.Query;


import javax.annotation.Resource;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.apache.log4j.*;



import com.ibm.domain.core.Territory;
import com.ibm.domain.core.IBUser;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Transactional
@Repository("Territory_Default_ActivityDao")
public class Territory_Default_ActivityDao   {

	//private Log log = LogFactory.getLog(getClass());
	private static Logger log = Logger.getLogger(Territory_Default_ActivityDao.class.getName());

	@Value("${create_Territory.sql}")
	private String create_Territory;
	@Value("${search_for_update_Territory.sql}")
	private String search_for_update_Territory;
	@Value("${update_Territory.sql}")
	private String update_Territory;
	@Value("${delete_Territory.sql}")
	private String delete_Territory;
	@Value("${get_all_Territory.sql}")
	private String get_all_Territory;


    @PersistenceContext
	private EntityManager entityManager;



	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform fetch operation of  Territory noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Territory object will return
	*@throws Exception
	*/

	public Territory territory_search_for_update(long id, IBUser user) throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("territory_search_for_update Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(search_for_update_Territory,Territory.class)

			.setParameter("id", id);;

			ArrayList<Territory> Territory_list =	(ArrayList<Territory>)result.getResultList();

			if(Territory_list  == null){

			log.error("territory_search_for_update Dao throws exception :" + "no Territory found" );
			throw new Exception("no Territory found");
			}
			log.info("Object returned from territory_search_for_update  Dao method !");
			return (Territory) Territory_list.get(0);

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("territory_search_for_update Dao throws exception : "+e.toString());

		}
		return null;


	}

	// auths not ready at this time

	/**
	*
	*The purpose of Dao method is to get list of  Territory noun from  database
	*
	*
	*@return List of Territory object will return
	*@throws Exception
	*/

	public ArrayList<Territory> get_all_territory() throws Exception {
		  log.setLevel(Level.INFO);
	      log.info("get_all_territory Dao started operation!");

		try{

			Query result =  entityManager.
			createNativeQuery(get_all_Territory,Territory.class)

;

			ArrayList<Territory> Territory_list =	(ArrayList<Territory>)result.getResultList();

			if(Territory_list .size() < 1){

			log.error("get_all_territory Dao throws exception :" + "no Territory found" );
			throw new Exception("no Territory found");
			}
			log.info("Object returned from get_all_territory  Dao method !");
			return (ArrayList<Territory>) Territory_list;

		}catch(Exception e){

			//new Exception(e.toString());  // this needs to be changed
			log.error("get_all_territory Dao throws exception : "+e.toString());

		}
		return null;


	}



	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform save operation of  Territory noun into database
	*@param Territory
	*@param user
	*@return Territory object will return
	*@throws Exception
	*/

	@Transactional
	public Territory create_territory(Territory Territory, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("create_territory Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(create_Territory)
			.setParameter("countryname", Territory.getCountryname())
			.setParameter("counntrycode", Territory.getCounntrycode())
			.setParameter("created_by", user == null ? 0:user.getId())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			int insertedId = query.executeUpdate();
					String lastIndex="select last_insert_id()";
					Query sql = entityManager.createNativeQuery(lastIndex);
					BigInteger new_id = (BigInteger) sql.getSingleResult();
					Territory.setId(new_id.longValue());
					System.out.println("create data---"+insertedId);

			log.info("Object returned from create_territory  Dao method !");

			return Territory;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (create_territory) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform update operation of  Territory noun into database
	*@param Territory
	*@param user
	*@return the_Territory object will return
	*@throws Exception
	*/

	@Transactional
	public Territory update_territory(Territory Territory, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("update_territory Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(update_Territory)
			.setParameter("id", Territory.getId())
			.setParameter("countryname", Territory.getCountryname())
			.setParameter("counntrycode", Territory.getCounntrycode())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			query.executeUpdate();

			log.info("Object returned from update_territory  Dao method !");

			return Territory;

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (update_territory) throws Exception : "+e.toString());

		}
		return null;



	}

	//auths not ready at this time

	/**
	*
	*The purpose of Dao method is to perform delete operation of  Territory noun from  database based on given noun id
	*@param  id
	*@param user
	*@return the_Territory id deleted based on id
	*@throws Exception
	*/

	@Transactional
	public String  delete_territory(long id, IBUser user) throws Exception {

	 	  log.setLevel(Level.INFO);
	      log.info("delete_territory Dao started operation!");

		try{
			Query query = entityManager
					.createNativeQuery(delete_Territory)
			.setParameter("id", id);

			query.executeUpdate();

			log.info("Object returned from delete_territory  Dao method !");

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			//System.out.println("DAOException: " + e.toString());
			log.error(" Dao method (delete_territory) throws Exception : "+e.toString());

		}
		return null;



	}



}