package com.ibm.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ibm.domain.core.AVLName;

import com.ibm.config.IBMSalesForecastSwaggerUIConstants;

import com.ibm.service.AVLName_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/AVLName_Default_Activity", description = "AVLName_Default_Activity of AVLName_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("AVLName_Default_ActivityController")
@RequestMapping("/AVLName_Default_Activity")
public class AVLName_Default_ActivityController  extends IBBaseController implements IBMSalesForecastSwaggerUIConstants {

private static Logger log = Logger.getLogger(AVLName_Default_ActivityController.class.getName());

	private AVLName_Default_ActivityService AVLName_Default_Activity_service;


	public AVLName_Default_ActivityService get_AVLName_Default_Activity_service() {
		return AVLName_Default_Activity_service;
	}


	@Resource(name="AVLName_Default_ActivityService")
	public void set_AVLName_Default_Activity_service(AVLName_Default_ActivityService AVLName_Default_Activity_service) {
		this.AVLName_Default_Activity_service = AVLName_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  AVLName noun into database
	* @param the_AVLName
	*@return AVLName object will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_AVLName", httpMethod = "POST",notes = "creates a noun of AVLName",response = AVLName.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_AVLName" ,headers="Accept=application/json")
    @ResponseBody
	public AVLName create_AVLName(@RequestBody AVLName the_AVLName) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_AVLName controller started operation!");

		AVLName a_AVLName;

		a_AVLName = AVLName_Default_Activity_service.create_avlname(the_AVLName, super.getUser());

		log.info("Object returned from create_AVLName method !");

		return a_AVLName;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  AVLName noun into database
	*@param the_AVLName
	*@return AVLNameobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_AVLName", httpMethod = "PUT",notes = "updates a noun of AVLName",response = AVLName.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_AVLName" ,headers="Accept=application/json")
    @ResponseBody
	public AVLName update_AVLName(@RequestBody AVLName the_AVLName) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_AVLName controller started operation!");

		AVLName a_AVLName;

		a_AVLName = AVLName_Default_Activity_service.update_avlname(the_AVLName, super.getUser());

		log.info("Object returned from update_AVLName method !");

		return a_AVLName;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  AVLName noun from  database based on given noun id
	*@param AVLName_id
	*@return AVLNameobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_AVLName/{AVLName_id}", httpMethod = "GET",notes = "updates a noun of AVLName",response = AVLName.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_AVLName/{AVLName_id}" ,headers="Accept=application/json")
    @ResponseBody
	public AVLName search_for_update_AVLName(@PathVariable("AVLName_id")long AVLName_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_AVLName controller started operation!");

		AVLName the_AVLName = new AVLName();

		the_AVLName = AVLName_Default_Activity_service.avlname_search_for_update(AVLName_id, super.getUser());

		log.info("Object returned from search_for_update_AVLName method !");

		return the_AVLName;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  AVLName noun from  database based on given noun id
	*@param AVLName_id
	*@return AVLNameobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_AVLName/{AVLName_id}", httpMethod = "DELETE",notes = "deletes a noun of AVLName",response = AVLName.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_AVLName/{AVLName_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_AVLName(@PathVariable("AVLName_id")long AVLName_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_AVLName controller started operation!");

		String service_return_msg = "";

		service_return_msg = AVLName_Default_Activity_service.delete_avlname(AVLName_id, super.getUser());

		log.info("Object returned from delete_AVLName method !");

		return service_return_msg;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  AVLName noun from  database
	*
	*@return List of AVLName objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_AVLName", httpMethod = "GET",notes = "special search that gets all values of AVLName",response = AVLName.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_AVLName" ,headers="Accept=application/json")
    @ResponseBody
	public List<AVLName> get_all_AVLName() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_AVLName controller started operation!");

		List<AVLName> AVLName_list = new ArrayList<AVLName>();

		AVLName_list = AVLName_Default_Activity_service.get_all_avlname();

		log.info("Object returned from get_all_AVLName method !");

		return AVLName_list;


	}




}