package com.ibm.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ibm.domain.core.Client;

import com.ibm.config.IBMSalesForecastSwaggerUIConstants;

import com.ibm.service.Client_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/Client_Default_Activity", description = "Client_Default_Activity of Client_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("Client_Default_ActivityController")
@RequestMapping("/Client_Default_Activity")
public class Client_Default_ActivityController  extends IBBaseController implements IBMSalesForecastSwaggerUIConstants {

private static Logger log = Logger.getLogger(Client_Default_ActivityController.class.getName());

	private Client_Default_ActivityService Client_Default_Activity_service;


	public Client_Default_ActivityService get_Client_Default_Activity_service() {
		return Client_Default_Activity_service;
	}


	@Resource(name="Client_Default_ActivityService")
	public void set_Client_Default_Activity_service(Client_Default_ActivityService Client_Default_Activity_service) {
		this.Client_Default_Activity_service = Client_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Client noun into database
	* @param the_Client
	*@return Client object will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Client", httpMethod = "POST",notes = "creates a noun of Client",response = Client.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Client" ,headers="Accept=application/json")
    @ResponseBody
	public Client create_Client(@RequestBody Client the_Client) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Client controller started operation!");

		Client a_Client;

		a_Client = Client_Default_Activity_service.create_client(the_Client, super.getUser());

		log.info("Object returned from create_Client method !");

		return a_Client;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Client noun into database
	*@param the_Client
	*@return Clientobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Client", httpMethod = "PUT",notes = "updates a noun of Client",response = Client.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Client" ,headers="Accept=application/json")
    @ResponseBody
	public Client update_Client(@RequestBody Client the_Client) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Client controller started operation!");

		Client a_Client;

		a_Client = Client_Default_Activity_service.update_client(the_Client, super.getUser());

		log.info("Object returned from update_Client method !");

		return a_Client;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Client noun from  database based on given noun id
	*@param Client_id
	*@return Clientobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Client/{Client_id}", httpMethod = "GET",notes = "updates a noun of Client",response = Client.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Client/{Client_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Client search_for_update_Client(@PathVariable("Client_id")long Client_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Client controller started operation!");

		Client the_Client = new Client();

		the_Client = Client_Default_Activity_service.client_search_for_update(Client_id, super.getUser());

		log.info("Object returned from search_for_update_Client method !");

		return the_Client;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Client noun from  database based on given noun id
	*@param Client_id
	*@return Clientobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Client/{Client_id}", httpMethod = "DELETE",notes = "deletes a noun of Client",response = Client.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Client/{Client_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Client(@PathVariable("Client_id")long Client_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Client controller started operation!");

		String service_return_msg = "";

		service_return_msg = Client_Default_Activity_service.delete_client(Client_id, super.getUser());

		log.info("Object returned from delete_Client method !");

		return service_return_msg;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Client noun from  database
	*
	*@return List of Client objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Client", httpMethod = "GET",notes = "special search that gets all values of Client",response = Client.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Client" ,headers="Accept=application/json")
    @ResponseBody
	public List<Client> get_all_Client() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Client controller started operation!");

		List<Client> Client_list = new ArrayList<Client>();

		Client_list = Client_Default_Activity_service.get_all_client();

		log.info("Object returned from get_all_Client method !");

		return Client_list;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Client noun from  database based on given noun id
	*@param Client_id
	*@return Clientobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_detail_Client/{Client_id}", httpMethod = "GET",notes = "special search for locking a noun details of Client",response = Client.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_detail_Client/{Client_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Client search_for_detail_Client(@PathVariable("Client_id")long Client_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_detail_Client controller started operation!");

		Client the_Client = new Client();

		the_Client = Client_Default_Activity_service.client_search_for_detail(Client_id, super.getUser());

		log.info("Object returned from search_for_detail_Client method !");

		return the_Client;


	}




}