package com.ibm.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ibm.domain.core.ComProduct;

import com.ibm.config.IBMSalesForecastSwaggerUIConstants;

import com.ibm.service.ComProduct_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/ComProduct_Default_Activity", description = "ComProduct_Default_Activity of ComProduct_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("ComProduct_Default_ActivityController")
@RequestMapping("/ComProduct_Default_Activity")
public class ComProduct_Default_ActivityController  extends IBBaseController implements IBMSalesForecastSwaggerUIConstants {

private static Logger log = Logger.getLogger(ComProduct_Default_ActivityController.class.getName());

	private ComProduct_Default_ActivityService ComProduct_Default_Activity_service;


	public ComProduct_Default_ActivityService get_ComProduct_Default_Activity_service() {
		return ComProduct_Default_Activity_service;
	}


	@Resource(name="ComProduct_Default_ActivityService")
	public void set_ComProduct_Default_Activity_service(ComProduct_Default_ActivityService ComProduct_Default_Activity_service) {
		this.ComProduct_Default_Activity_service = ComProduct_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  ComProduct noun into database
	* @param the_ComProduct
	*@return ComProduct object will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_ComProduct", httpMethod = "POST",notes = "creates a noun of ComProduct",response = ComProduct.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_ComProduct" ,headers="Accept=application/json")
    @ResponseBody
	public ComProduct create_ComProduct(@RequestBody ComProduct the_ComProduct) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_ComProduct controller started operation!");

		ComProduct a_ComProduct;

		a_ComProduct = ComProduct_Default_Activity_service.create_comproduct(the_ComProduct, super.getUser());

		log.info("Object returned from create_ComProduct method !");

		return a_ComProduct;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  ComProduct noun into database
	*@param the_ComProduct
	*@return ComProductobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_ComProduct", httpMethod = "PUT",notes = "updates a noun of ComProduct",response = ComProduct.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_ComProduct" ,headers="Accept=application/json")
    @ResponseBody
	public ComProduct update_ComProduct(@RequestBody ComProduct the_ComProduct) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_ComProduct controller started operation!");

		ComProduct a_ComProduct;

		a_ComProduct = ComProduct_Default_Activity_service.update_comproduct(the_ComProduct, super.getUser());

		log.info("Object returned from update_ComProduct method !");

		return a_ComProduct;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  ComProduct noun from  database based on given noun id
	*@param ComProduct_id
	*@return ComProductobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_ComProduct/{ComProduct_id}", httpMethod = "GET",notes = "updates a noun of ComProduct",response = ComProduct.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_ComProduct/{ComProduct_id}" ,headers="Accept=application/json")
    @ResponseBody
	public ComProduct search_for_update_ComProduct(@PathVariable("ComProduct_id")long ComProduct_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_ComProduct controller started operation!");

		ComProduct the_ComProduct = new ComProduct();

		the_ComProduct = ComProduct_Default_Activity_service.comproduct_search_for_update(ComProduct_id, super.getUser());

		log.info("Object returned from search_for_update_ComProduct method !");

		return the_ComProduct;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  ComProduct noun from  database based on given noun id
	*@param ComProduct_id
	*@return ComProductobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_ComProduct/{ComProduct_id}", httpMethod = "DELETE",notes = "deletes a noun of ComProduct",response = ComProduct.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_ComProduct/{ComProduct_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_ComProduct(@PathVariable("ComProduct_id")long ComProduct_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_ComProduct controller started operation!");

		String service_return_msg = "";

		service_return_msg = ComProduct_Default_Activity_service.delete_comproduct(ComProduct_id, super.getUser());

		log.info("Object returned from delete_ComProduct method !");

		return service_return_msg;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  ComProduct noun from  database
	*
	*@return List of ComProduct objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_ComProduct", httpMethod = "GET",notes = "special search that gets all values of ComProduct",response = ComProduct.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_ComProduct" ,headers="Accept=application/json")
    @ResponseBody
	public List<ComProduct> get_all_ComProduct() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_ComProduct controller started operation!");

		List<ComProduct> ComProduct_list = new ArrayList<ComProduct>();

		ComProduct_list = ComProduct_Default_Activity_service.get_all_comproduct();

		log.info("Object returned from get_all_ComProduct method !");

		return ComProduct_list;


	}




}