package com.ibm.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ibm.domain.core.MonthEnd;

import com.ibm.config.IBMSalesForecastSwaggerUIConstants;

import com.ibm.service.MonthEnd_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/MonthEnd_Default_Activity", description = "MonthEnd_Default_Activity of MonthEnd_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("MonthEnd_Default_ActivityController")
@RequestMapping("/MonthEnd_Default_Activity")
public class MonthEnd_Default_ActivityController  extends IBBaseController implements IBMSalesForecastSwaggerUIConstants {

private static Logger log = Logger.getLogger(MonthEnd_Default_ActivityController.class.getName());

	private MonthEnd_Default_ActivityService MonthEnd_Default_Activity_service;


	public MonthEnd_Default_ActivityService get_MonthEnd_Default_Activity_service() {
		return MonthEnd_Default_Activity_service;
	}


	@Resource(name="MonthEnd_Default_ActivityService")
	public void set_MonthEnd_Default_Activity_service(MonthEnd_Default_ActivityService MonthEnd_Default_Activity_service) {
		this.MonthEnd_Default_Activity_service = MonthEnd_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  MonthEnd noun into database
	* @param the_MonthEnd
	*@return MonthEnd object will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_MonthEnd", httpMethod = "POST",notes = "creates a noun of MonthEnd",response = MonthEnd.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_MonthEnd" ,headers="Accept=application/json")
    @ResponseBody
	public MonthEnd create_MonthEnd(@RequestBody MonthEnd the_MonthEnd) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_MonthEnd controller started operation!");

		MonthEnd a_MonthEnd;

		a_MonthEnd = MonthEnd_Default_Activity_service.create_monthend(the_MonthEnd, super.getUser());

		log.info("Object returned from create_MonthEnd method !");

		return a_MonthEnd;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  MonthEnd noun into database
	*@param the_MonthEnd
	*@return MonthEndobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_MonthEnd", httpMethod = "PUT",notes = "updates a noun of MonthEnd",response = MonthEnd.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_MonthEnd" ,headers="Accept=application/json")
    @ResponseBody
	public MonthEnd update_MonthEnd(@RequestBody MonthEnd the_MonthEnd) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_MonthEnd controller started operation!");

		MonthEnd a_MonthEnd;

		a_MonthEnd = MonthEnd_Default_Activity_service.update_monthend(the_MonthEnd, super.getUser());

		log.info("Object returned from update_MonthEnd method !");

		return a_MonthEnd;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  MonthEnd noun from  database based on given noun id
	*@param MonthEnd_id
	*@return MonthEndobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_MonthEnd/{MonthEnd_id}", httpMethod = "GET",notes = "updates a noun of MonthEnd",response = MonthEnd.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_MonthEnd/{MonthEnd_id}" ,headers="Accept=application/json")
    @ResponseBody
	public MonthEnd search_for_update_MonthEnd(@PathVariable("MonthEnd_id")long MonthEnd_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_MonthEnd controller started operation!");

		MonthEnd the_MonthEnd = new MonthEnd();

		the_MonthEnd = MonthEnd_Default_Activity_service.monthend_search_for_update(MonthEnd_id, super.getUser());

		log.info("Object returned from search_for_update_MonthEnd method !");

		return the_MonthEnd;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  MonthEnd noun from  database based on given noun id
	*@param MonthEnd_id
	*@return MonthEndobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_MonthEnd/{MonthEnd_id}", httpMethod = "DELETE",notes = "deletes a noun of MonthEnd",response = MonthEnd.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_MonthEnd/{MonthEnd_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_MonthEnd(@PathVariable("MonthEnd_id")long MonthEnd_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_MonthEnd controller started operation!");

		String service_return_msg = "";

		service_return_msg = MonthEnd_Default_Activity_service.delete_monthend(MonthEnd_id, super.getUser());

		log.info("Object returned from delete_MonthEnd method !");

		return service_return_msg;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  MonthEnd noun from  database
	*
	*@return List of MonthEnd objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_MonthEnd", httpMethod = "GET",notes = "special search that gets all values of MonthEnd",response = MonthEnd.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_MonthEnd" ,headers="Accept=application/json")
    @ResponseBody
	public List<MonthEnd> get_all_MonthEnd() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_MonthEnd controller started operation!");

		List<MonthEnd> MonthEnd_list = new ArrayList<MonthEnd>();

		MonthEnd_list = MonthEnd_Default_Activity_service.get_all_monthend();

		log.info("Object returned from get_all_MonthEnd method !");

		return MonthEnd_list;


	}




}