package com.ibm.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ibm.domain.core.Note;

import com.ibm.config.IBMSalesForecastSwaggerUIConstants;

import com.ibm.service.Note_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/note_Default_Activity", description = "note_Default_Activity of note_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("Note_Default_ActivityController")
@RequestMapping("/note_Default_Activity")
public class Note_Default_ActivityController  extends IBBaseController implements IBMSalesForecastSwaggerUIConstants {

private static Logger log = Logger.getLogger(Note_Default_ActivityController.class.getName());

	private Note_Default_ActivityService note_Default_Activity_service;


	public Note_Default_ActivityService get_note_Default_Activity_service() {
		return note_Default_Activity_service;
	}


	@Resource(name="Note_Default_ActivityService")
	public void set_note_Default_Activity_service(Note_Default_ActivityService note_Default_Activity_service) {
		this.note_Default_Activity_service = note_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Note noun into database
	* @param the_Note
	*@return Note object will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Note", httpMethod = "POST",notes = "creates a noun of Note",response = Note.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Note" ,headers="Accept=application/json")
    @ResponseBody
	public Note create_Note(@RequestBody Note the_Note) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Note controller started operation!");

		Note a_Note;

		a_Note = note_Default_Activity_service.create_note(the_Note, super.getUser());

		log.info("Object returned from create_Note method !");

		return a_Note;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Note noun into database
	*@param the_Note
	*@return Noteobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Note", httpMethod = "PUT",notes = "updates a noun of Note",response = Note.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Note" ,headers="Accept=application/json")
    @ResponseBody
	public Note update_Note(@RequestBody Note the_Note) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Note controller started operation!");

		Note a_Note;

		a_Note = note_Default_Activity_service.update_note(the_Note, super.getUser());

		log.info("Object returned from update_Note method !");

		return a_Note;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Note noun from  database based on given noun id
	*@param Note_id
	*@return Noteobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Note/{Note_id}", httpMethod = "GET",notes = "updates a noun of Note",response = Note.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Note/{Note_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Note search_for_update_Note(@PathVariable("Note_id")long Note_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Note controller started operation!");

		Note the_Note = new Note();

		the_Note = note_Default_Activity_service.note_search_for_update(Note_id, super.getUser());

		log.info("Object returned from search_for_update_Note method !");

		return the_Note;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Note noun from  database based on given noun id
	*@param Note_id
	*@return Noteobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Note/{Note_id}", httpMethod = "DELETE",notes = "deletes a noun of Note",response = Note.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Note/{Note_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Note(@PathVariable("Note_id")long Note_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Note controller started operation!");

		String service_return_msg = "";

		service_return_msg = note_Default_Activity_service.delete_note(Note_id, super.getUser());

		log.info("Object returned from delete_Note method !");

		return service_return_msg;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Note noun from  database
	*
	*@return List of Note objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Note", httpMethod = "GET",notes = "special search that gets all values of Note",response = Note.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Note" ,headers="Accept=application/json")
    @ResponseBody
	public List<Note> get_all_Note() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Note controller started operation!");

		List<Note> Note_list = new ArrayList<Note>();

		Note_list = note_Default_Activity_service.get_all_note();

		log.info("Object returned from get_all_Note method !");

		return Note_list;


	}




}