package com.ibm.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ibm.domain.core.Offering;

import com.ibm.config.IBMSalesForecastSwaggerUIConstants;

import com.ibm.service.Offering_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/Offering_Default_Activity", description = "Offering_Default_Activity of Offering_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("Offering_Default_ActivityController")
@RequestMapping("/Offering_Default_Activity")
public class Offering_Default_ActivityController  extends IBBaseController implements IBMSalesForecastSwaggerUIConstants {

private static Logger log = Logger.getLogger(Offering_Default_ActivityController.class.getName());

	private Offering_Default_ActivityService Offering_Default_Activity_service;


	public Offering_Default_ActivityService get_Offering_Default_Activity_service() {
		return Offering_Default_Activity_service;
	}


	@Resource(name="Offering_Default_ActivityService")
	public void set_Offering_Default_Activity_service(Offering_Default_ActivityService Offering_Default_Activity_service) {
		this.Offering_Default_Activity_service = Offering_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Offering noun into database
	* @param the_Offering
	*@return Offering object will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Offering", httpMethod = "POST",notes = "creates a noun of Offering",response = Offering.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Offering" ,headers="Accept=application/json")
    @ResponseBody
	public Offering create_Offering(@RequestBody Offering the_Offering) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Offering controller started operation!");

		Offering a_Offering;

		a_Offering = Offering_Default_Activity_service.create_offering(the_Offering, super.getUser());

		log.info("Object returned from create_Offering method !");

		return a_Offering;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Offering noun into database
	*@param the_Offering
	*@return Offeringobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Offering", httpMethod = "PUT",notes = "updates a noun of Offering",response = Offering.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Offering" ,headers="Accept=application/json")
    @ResponseBody
	public Offering update_Offering(@RequestBody Offering the_Offering) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Offering controller started operation!");

		Offering a_Offering;

		a_Offering = Offering_Default_Activity_service.update_offering(the_Offering, super.getUser());

		log.info("Object returned from update_Offering method !");

		return a_Offering;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Offering noun from  database based on given noun id
	*@param Offering_id
	*@return Offeringobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Offering/{Offering_id}", httpMethod = "GET",notes = "updates a noun of Offering",response = Offering.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Offering/{Offering_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Offering search_for_update_Offering(@PathVariable("Offering_id")long Offering_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Offering controller started operation!");

		Offering the_Offering = new Offering();

		the_Offering = Offering_Default_Activity_service.offering_search_for_update(Offering_id, super.getUser());

		log.info("Object returned from search_for_update_Offering method !");

		return the_Offering;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Offering noun from  database based on given noun id
	*@param Offering_id
	*@return Offeringobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Offering/{Offering_id}", httpMethod = "DELETE",notes = "deletes a noun of Offering",response = Offering.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Offering/{Offering_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Offering(@PathVariable("Offering_id")long Offering_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Offering controller started operation!");

		String service_return_msg = "";

		service_return_msg = Offering_Default_Activity_service.delete_offering(Offering_id, super.getUser());

		log.info("Object returned from delete_Offering method !");

		return service_return_msg;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Offering noun from  database
	*
	*@return List of Offering objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Offering", httpMethod = "GET",notes = "special search that gets all values of Offering",response = Offering.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Offering" ,headers="Accept=application/json")
    @ResponseBody
	public List<Offering> get_all_Offering() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Offering controller started operation!");

		List<Offering> Offering_list = new ArrayList<Offering>();

		Offering_list = Offering_Default_Activity_service.get_all_offering();

		log.info("Object returned from get_all_Offering method !");

		return Offering_list;


	}




}