package com.ibm.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ibm.domain.core.Practice;

import com.ibm.config.IBMSalesForecastSwaggerUIConstants;

import com.ibm.service.Practice_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/Practice_Default_Activity", description = "Practice_Default_Activity of Practice_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("Practice_Default_ActivityController")
@RequestMapping("/Practice_Default_Activity")
public class Practice_Default_ActivityController  extends IBBaseController implements IBMSalesForecastSwaggerUIConstants {

private static Logger log = Logger.getLogger(Practice_Default_ActivityController.class.getName());

	private Practice_Default_ActivityService Practice_Default_Activity_service;


	public Practice_Default_ActivityService get_Practice_Default_Activity_service() {
		return Practice_Default_Activity_service;
	}


	@Resource(name="Practice_Default_ActivityService")
	public void set_Practice_Default_Activity_service(Practice_Default_ActivityService Practice_Default_Activity_service) {
		this.Practice_Default_Activity_service = Practice_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Practice noun into database
	* @param the_Practice
	*@return Practice object will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Practice", httpMethod = "POST",notes = "creates a noun of Practice",response = Practice.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Practice" ,headers="Accept=application/json")
    @ResponseBody
	public Practice create_Practice(@RequestBody Practice the_Practice) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Practice controller started operation!");

		Practice a_Practice;

		a_Practice = Practice_Default_Activity_service.create_practice(the_Practice, super.getUser());

		log.info("Object returned from create_Practice method !");

		return a_Practice;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Practice noun into database
	*@param the_Practice
	*@return Practiceobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Practice", httpMethod = "PUT",notes = "updates a noun of Practice",response = Practice.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Practice" ,headers="Accept=application/json")
    @ResponseBody
	public Practice update_Practice(@RequestBody Practice the_Practice) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Practice controller started operation!");

		Practice a_Practice;

		a_Practice = Practice_Default_Activity_service.update_practice(the_Practice, super.getUser());

		log.info("Object returned from update_Practice method !");

		return a_Practice;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Practice noun from  database based on given noun id
	*@param Practice_id
	*@return Practiceobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Practice/{Practice_id}", httpMethod = "GET",notes = "updates a noun of Practice",response = Practice.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Practice/{Practice_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Practice search_for_update_Practice(@PathVariable("Practice_id")long Practice_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Practice controller started operation!");

		Practice the_Practice = new Practice();

		the_Practice = Practice_Default_Activity_service.practice_search_for_update(Practice_id, super.getUser());

		log.info("Object returned from search_for_update_Practice method !");

		return the_Practice;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Practice noun from  database based on given noun id
	*@param Practice_id
	*@return Practiceobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Practice/{Practice_id}", httpMethod = "DELETE",notes = "deletes a noun of Practice",response = Practice.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Practice/{Practice_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Practice(@PathVariable("Practice_id")long Practice_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Practice controller started operation!");

		String service_return_msg = "";

		service_return_msg = Practice_Default_Activity_service.delete_practice(Practice_id, super.getUser());

		log.info("Object returned from delete_Practice method !");

		return service_return_msg;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Practice noun from  database
	*
	*@return List of Practice objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Practice", httpMethod = "GET",notes = "special search that gets all values of Practice",response = Practice.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Practice" ,headers="Accept=application/json")
    @ResponseBody
	public List<Practice> get_all_Practice() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Practice controller started operation!");

		List<Practice> Practice_list = new ArrayList<Practice>();

		Practice_list = Practice_Default_Activity_service.get_all_practice();

		log.info("Object returned from get_all_Practice method !");

		return Practice_list;


	}




}