package com.ibm.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ibm.domain.core.Region;

import com.ibm.config.IBMSalesForecastSwaggerUIConstants;

import com.ibm.service.Region_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/Region_Default_Activity", description = "Region_Default_Activity of Region_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("Region_Default_ActivityController")
@RequestMapping("/Region_Default_Activity")
public class Region_Default_ActivityController  extends IBBaseController implements IBMSalesForecastSwaggerUIConstants {

private static Logger log = Logger.getLogger(Region_Default_ActivityController.class.getName());

	private Region_Default_ActivityService Region_Default_Activity_service;


	public Region_Default_ActivityService get_Region_Default_Activity_service() {
		return Region_Default_Activity_service;
	}


	@Resource(name="Region_Default_ActivityService")
	public void set_Region_Default_Activity_service(Region_Default_ActivityService Region_Default_Activity_service) {
		this.Region_Default_Activity_service = Region_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Region noun into database
	* @param the_Region
	*@return Region object will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Region", httpMethod = "POST",notes = "creates a noun of Region",response = Region.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Region" ,headers="Accept=application/json")
    @ResponseBody
	public Region create_Region(@RequestBody Region the_Region) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Region controller started operation!");

		Region a_Region;

		a_Region = Region_Default_Activity_service.create_region(the_Region, super.getUser());

		log.info("Object returned from create_Region method !");

		return a_Region;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Region noun into database
	*@param the_Region
	*@return Regionobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Region", httpMethod = "PUT",notes = "updates a noun of Region",response = Region.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Region" ,headers="Accept=application/json")
    @ResponseBody
	public Region update_Region(@RequestBody Region the_Region) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Region controller started operation!");

		Region a_Region;

		a_Region = Region_Default_Activity_service.update_region(the_Region, super.getUser());

		log.info("Object returned from update_Region method !");

		return a_Region;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Region noun from  database based on given noun id
	*@param Region_id
	*@return Regionobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Region/{Region_id}", httpMethod = "GET",notes = "updates a noun of Region",response = Region.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Region/{Region_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Region search_for_update_Region(@PathVariable("Region_id")long Region_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Region controller started operation!");

		Region the_Region = new Region();

		the_Region = Region_Default_Activity_service.region_search_for_update(Region_id, super.getUser());

		log.info("Object returned from search_for_update_Region method !");

		return the_Region;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Region noun from  database based on given noun id
	*@param Region_id
	*@return Regionobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Region/{Region_id}", httpMethod = "DELETE",notes = "deletes a noun of Region",response = Region.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Region/{Region_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Region(@PathVariable("Region_id")long Region_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Region controller started operation!");

		String service_return_msg = "";

		service_return_msg = Region_Default_Activity_service.delete_region(Region_id, super.getUser());

		log.info("Object returned from delete_Region method !");

		return service_return_msg;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Region noun from  database
	*
	*@return List of Region objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Region", httpMethod = "GET",notes = "special search that gets all values of Region",response = Region.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Region" ,headers="Accept=application/json")
    @ResponseBody
	public List<Region> get_all_Region() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Region controller started operation!");

		List<Region> Region_list = new ArrayList<Region>();

		Region_list = Region_Default_Activity_service.get_all_region();

		log.info("Object returned from get_all_Region method !");

		return Region_list;


	}




}