package com.ibm.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ibm.domain.core.RevenueType;

import com.ibm.config.IBMSalesForecastSwaggerUIConstants;

import com.ibm.service.RevenueType_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/RevenueType_Default_Activity", description = "RevenueType_Default_Activity of RevenueType_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("RevenueType_Default_ActivityController")
@RequestMapping("/RevenueType_Default_Activity")
public class RevenueType_Default_ActivityController  extends IBBaseController implements IBMSalesForecastSwaggerUIConstants {

private static Logger log = Logger.getLogger(RevenueType_Default_ActivityController.class.getName());

	private RevenueType_Default_ActivityService RevenueType_Default_Activity_service;


	public RevenueType_Default_ActivityService get_RevenueType_Default_Activity_service() {
		return RevenueType_Default_Activity_service;
	}


	@Resource(name="RevenueType_Default_ActivityService")
	public void set_RevenueType_Default_Activity_service(RevenueType_Default_ActivityService RevenueType_Default_Activity_service) {
		this.RevenueType_Default_Activity_service = RevenueType_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  RevenueType noun into database
	* @param the_RevenueType
	*@return RevenueType object will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_RevenueType", httpMethod = "POST",notes = "creates a noun of RevenueType",response = RevenueType.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_RevenueType" ,headers="Accept=application/json")
    @ResponseBody
	public RevenueType create_RevenueType(@RequestBody RevenueType the_RevenueType) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_RevenueType controller started operation!");

		RevenueType a_RevenueType;

		a_RevenueType = RevenueType_Default_Activity_service.create_revenuetype(the_RevenueType, super.getUser());

		log.info("Object returned from create_RevenueType method !");

		return a_RevenueType;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  RevenueType noun into database
	*@param the_RevenueType
	*@return RevenueTypeobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_RevenueType", httpMethod = "PUT",notes = "updates a noun of RevenueType",response = RevenueType.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_RevenueType" ,headers="Accept=application/json")
    @ResponseBody
	public RevenueType update_RevenueType(@RequestBody RevenueType the_RevenueType) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_RevenueType controller started operation!");

		RevenueType a_RevenueType;

		a_RevenueType = RevenueType_Default_Activity_service.update_revenuetype(the_RevenueType, super.getUser());

		log.info("Object returned from update_RevenueType method !");

		return a_RevenueType;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  RevenueType noun from  database based on given noun id
	*@param RevenueType_id
	*@return RevenueTypeobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_RevenueType/{RevenueType_id}", httpMethod = "GET",notes = "updates a noun of RevenueType",response = RevenueType.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_RevenueType/{RevenueType_id}" ,headers="Accept=application/json")
    @ResponseBody
	public RevenueType search_for_update_RevenueType(@PathVariable("RevenueType_id")long RevenueType_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_RevenueType controller started operation!");

		RevenueType the_RevenueType = new RevenueType();

		the_RevenueType = RevenueType_Default_Activity_service.revenuetype_search_for_update(RevenueType_id, super.getUser());

		log.info("Object returned from search_for_update_RevenueType method !");

		return the_RevenueType;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  RevenueType noun from  database based on given noun id
	*@param RevenueType_id
	*@return RevenueTypeobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_RevenueType/{RevenueType_id}", httpMethod = "DELETE",notes = "deletes a noun of RevenueType",response = RevenueType.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_RevenueType/{RevenueType_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_RevenueType(@PathVariable("RevenueType_id")long RevenueType_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_RevenueType controller started operation!");

		String service_return_msg = "";

		service_return_msg = RevenueType_Default_Activity_service.delete_revenuetype(RevenueType_id, super.getUser());

		log.info("Object returned from delete_RevenueType method !");

		return service_return_msg;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  RevenueType noun from  database
	*
	*@return List of RevenueType objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_RevenueType", httpMethod = "GET",notes = "special search that gets all values of RevenueType",response = RevenueType.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_RevenueType" ,headers="Accept=application/json")
    @ResponseBody
	public List<RevenueType> get_all_RevenueType() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_RevenueType controller started operation!");

		List<RevenueType> RevenueType_list = new ArrayList<RevenueType>();

		RevenueType_list = RevenueType_Default_Activity_service.get_all_revenuetype();

		log.info("Object returned from get_all_RevenueType method !");

		return RevenueType_list;


	}




}