package com.ibm.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ibm.domain.core.Role;

import com.ibm.config.IBMSalesForecastSwaggerUIConstants;

import com.ibm.service.Role_Default_ActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/Role_Default_Activity", description = "Role_Default_Activity of Role_Default_Activity",produces = "application/json")
@CrossOrigin
@Controller("Role_Default_ActivityController")
@RequestMapping("/Role_Default_Activity")
public class Role_Default_ActivityController  extends IBBaseController implements IBMSalesForecastSwaggerUIConstants {

private static Logger log = Logger.getLogger(Role_Default_ActivityController.class.getName());

	private Role_Default_ActivityService Role_Default_Activity_service;


	public Role_Default_ActivityService get_Role_Default_Activity_service() {
		return Role_Default_Activity_service;
	}


	@Resource(name="Role_Default_ActivityService")
	public void set_Role_Default_Activity_service(Role_Default_ActivityService Role_Default_Activity_service) {
		this.Role_Default_Activity_service = Role_Default_Activity_service;
	}




	//auths not ready at this time
	/**
	*The purpose of this method is to perform save operation of  Role noun into database
	* @param the_Role
	*@return Role object will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/create_Role", httpMethod = "POST",notes = "creates a noun of Role",response = Role.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.POST,value = "/create_Role" ,headers="Accept=application/json")
    @ResponseBody
	public Role create_Role(@RequestBody Role the_Role) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("create_Role controller started operation!");

		Role a_Role;

		a_Role = Role_Default_Activity_service.create_role(the_Role, super.getUser());

		log.info("Object returned from create_Role method !");

		return a_Role;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform update operation of  Role noun into database
	*@param the_Role
	*@return Roleobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/update_Role", httpMethod = "PUT",notes = "updates a noun of Role",response = Role.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.PUT,value = "/update_Role" ,headers="Accept=application/json")
    @ResponseBody
	public Role update_Role(@RequestBody Role the_Role) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("update_Role controller started operation!");

		Role a_Role;

		a_Role = Role_Default_Activity_service.update_role(the_Role, super.getUser());

		log.info("Object returned from update_Role method !");

		return a_Role;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform fetch operation of  Role noun from  database based on given noun id
	*@param Role_id
	*@return Roleobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/search_for_update_Role/{Role_id}", httpMethod = "GET",notes = "updates a noun of Role",response = Role.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_Role/{Role_id}" ,headers="Accept=application/json")
    @ResponseBody
	public Role search_for_update_Role(@PathVariable("Role_id")long Role_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("search_for_update_Role controller started operation!");

		Role the_Role = new Role();

		the_Role = Role_Default_Activity_service.role_search_for_update(Role_id, super.getUser());

		log.info("Object returned from search_for_update_Role method !");

		return the_Role;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to perform delete operation of  Role noun from  database based on given noun id
	*@param Role_id
	*@return Roleobject will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/delete_Role/{Role_id}", httpMethod = "DELETE",notes = "deletes a noun of Role",response = Role.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_Role/{Role_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_Role(@PathVariable("Role_id")long Role_id) throws Exception {

		log.setLevel(Level.INFO);
	    log.info("delete_Role controller started operation!");

		String service_return_msg = "";

		service_return_msg = Role_Default_Activity_service.delete_role(Role_id, super.getUser());

		log.info("Object returned from delete_Role method !");

		return service_return_msg;


	}


	//auths not ready at this time
	/**
	*The purpose of this method is to get list of  Role noun from  database
	*
	*@return List of Role objects will return
	*@throws Exception
	*
	*
	*/


	@ApiOperation(value = "/get_all_Role", httpMethod = "GET",notes = "special search that gets all values of Role",response = Role.class)
	@ApiResponses(value = {
		@ApiResponse(code = 200, message = IBMSalesForecastSwaggerUIConstants.SUCCESS),
	    @ApiResponse(code = 404, message = IBMSalesForecastSwaggerUIConstants.NOT_FOUND),
	    @ApiResponse(code = 500, message = IBMSalesForecastSwaggerUIConstants.INTERNAL_SERVER_ERROR),
	    @ApiResponse(code = 400, message = IBMSalesForecastSwaggerUIConstants.BAD_REQUEST),
	    @ApiResponse(code = 412, message = IBMSalesForecastSwaggerUIConstants.PRE_CONDITION_FAILED) })


	@RequestMapping(method = RequestMethod.GET,value = "/get_all_Role" ,headers="Accept=application/json")
    @ResponseBody
	public List<Role> get_all_Role() throws Exception {

		log.setLevel(Level.INFO);
	    log.info("get_all_Role controller started operation!");

		List<Role> Role_list = new ArrayList<Role>();

		Role_list = Role_Default_Activity_service.get_all_role();

		log.info("Object returned from get_all_Role method !");

		return Role_list;


	}




}